// GENERATED by scripts/gen-announcer.mjs — DO NOT EDIT.
//
// UT99's announcer, and the rules for when it speaks. Every rule below was read out of
// Botpack's own UnrealScript rather than remembered:
//
//   FIRST BLOOD   DeathMatchPlus guards it with a bFirstBlood flag — once a match, on
//                 the first kill, and everybody hears it.
//
//   MULTI-KILL    DeathMessagePlus:
//                     if (Level.TimeSeconds - LastKillTime < 3) MultiLevel++;
//                     else MultiLevel = 0;
//                 so it is a 3-second window between kills, not a count. Level 1 is
//                 doublekill, 2 is multikill, 3 is ultrakill, and 4 or more is
//                 monsterkill. It goes to the KILLER alone, not the room.
//
//   SPREE         DeathMatchPlus calls NotifySpree once a spree passes 4, and NotifySpree
//                 speaks at EXACTLY 5, 10, 15, 20, 25 — every other number returns
//                 without a word. Dying resets it. Everybody hears it.
//
// megakill and triplekill are in Announcer.uax and are deliberately absent: UT99's own
// MultiKillMessage never reaches for them.

/** Where the files live. The key IS the file name. */
const ANNOUNCER_DIR = "assets/audio/ut/announcer";

/** Every sound, for preloading. */
const ANNOUNCEMENTS = ["firstblood","doublekill","multikill","ultrakill","monsterkill","killingspree","rampage","dominating","unstoppable","godlike","prepare","winner","lostmatch","capture","headshot"];

const FIRST_BLOOD = "firstblood";
const MULTI_KILL = ["doublekill","multikill","ultrakill","monsterkill"];
const MULTI_KILL_WINDOW_MS = 3000;
const SPREE_AT = [5,10,15,20,25];
const SPREE = ["killingspree","rampage","dominating","unstoppable","godlike"];
const MATCH = {"start":"prepare","won":"winner","lost":"lostmatch"};
const CAPTURE = "capture";
const HEADSHOT = "headshot";

/** The file for a key, or null if it is not one of ours. */
function announcementUrl(key) {
  return ANNOUNCEMENTS.includes(key) ? `${ANNOUNCER_DIR}/${key}.mp3` : null;
}

/**
 * What a killer has just earned by killing again, or null.
 *
 * `level` is their MultiLevel AFTER incrementing — 1 for the second kill inside the
 * window. Anything past the end of the list stays on the last one, which is how UT99
 * folds every switch from 4 to 9 onto MonsterKill.
 */
function multiKillSound(level) {
  if (level < 1) return null;
  return MULTI_KILL[Math.min(level, MULTI_KILL.length) - 1];
}

/** The spree sound for an exact count, or null. UT99 speaks at those numbers and no others. */
function spreeSound(count) {
  const i = SPREE_AT.indexOf(count);
  return i < 0 ? null : SPREE[i];
}

module.exports = {
  ANNOUNCER_DIR,
  ANNOUNCEMENTS,
  FIRST_BLOOD,
  MULTI_KILL_WINDOW_MS,
  MATCH,
  CAPTURE,
  HEADSHOT,
  announcementUrl,
  multiKillSound,
  spreeSound,
};
