// GENERATED by scripts/gen-characters.mjs — DO NOT EDIT.
//
// The server half of the character roster. It never needs the URLs — only how many
// variants exist and which is which — so this is the list and a picker, nothing more.
//
// WHY THE SERVER CHOOSES. If each client picked its own body for a player, two people
// would see the same bot as different characters, and a bot would change identity on
// every reconnect. The pick is a server fact like the team, broadcast in publicPlayer().

const VARIANTS = [["boss","xan"],["commando","gorn"],["commando","graves"],["commando","kragoth"],["commando","malakai"],["fcommando","gromida"],["fcommando","ivana"],["fcommando","jayce"],["fcommando","nikita"],["nali","default"],["sgirl","aryss"],["sgirl","athena"],["sgirl","ryanna"],["sgirl","tasha"],["skaarj","baetal"],["skaarj","disconnect"],["skaarj","pharoh"],["skaarj","skrilax"],["soldier","malcom"],["soldier","manwell"],["soldier","radkin"],["soldier","rankin"],["warcow","default"]];
const CHARACTER_COUNT = VARIANTS.length;

/**
 * Pick a character for a new player, avoiding the ones already on the map so a
 * ten-bot match is ten different bodies rather than the same face four times.
 * `taken` is any iterable of indices currently in use.
 */
function pickCharacter(taken) {
  const used = new Set(taken);
  const free = [];
  for (let i = 0; i < CHARACTER_COUNT; i++) if (!used.has(i)) free.push(i);
  const pool = free.length ? free : Array.from({ length: CHARACTER_COUNT }, (_, i) => i);
  return pool[Math.floor(Math.random() * pool.length)];
}

module.exports = { VARIANTS, CHARACTER_COUNT, pickCharacter };
