// GENERATED by scripts/gen-map-actors.mjs — DO NOT EDIT.
//
// CTF-Face's real actor placements, converted from Unreal Units to this game's scene
// coordinates by src/shared/map-transform.js. Regenerate with:
//
//   node scripts/gen-map-actors.mjs
//
// Source: scripts/data/ctf-face-actors.json (2 flag bases,
// 20 player starts, 56 pickups). Every x and z here starts
// as Epic's, put through the measured similarity transform.
//
// Then everything that stands on something is SNAPPED TO THE SHIPPED NAVMESH: y comes
// from the polygon under the actor, and where the fan model has a hole the original level
// does not, the x/z is walked to the nearest covered spot (5 of them needed it,
// by at most 1.6 units — the blue flag base, three PlayerStarts and one MedBox).
// The fit is good to ~0.25 units outdoors and worse than a unit inside the tower alcoves,
// which is the difference between a flag stand on the ground and one hanging in the air.
//
// `ry` is a three.js rotation.y in RADIANS, already through the handedness flip.
// `ut` names the original actor, so any number here can be traced back to the level.

// The pedestal ground both bases stand on: the navmesh's lowest polygon.
const GROUND_Y = -0.41;

// Where the flags actually live in CTF-Face: at the FOOT of each tower, not on the roof.
// The roofs are sniper decks. `y` is the navmesh surface plus the 0.05 lift, so the stand
// sits ON the ground rather than the ~0.5 above it the raw fit gives (there is no plinth
// modelled in the fan map). Facing (`ry`) is the base's own, which is what the flag stand
// should be turned to.
const FLAG_HOMES = {
  red: {"x":101.18,"y":-0.36,"z":5,"ry":1.522,"ut":"FlagBase0"},
  blue: {"x":-75.42,"y":-0.32,"z":-20.38,"ry":1.486,"ut":"FlagBase1"},
};

// The tower roof decks: centre, walkable height, and a half-extent box around each that
// covers the whole tower column. Used by the anti-cheat to answer "could a player
// legitimately be this high here?" — the only two places on the map where the answer
// above the bridge is yes.
const TOWER_ROOFS = {
  red: {"x":98.08,"y":71.06,"z":-11.39},
  blue: {"x":-75.67,"y":71.06,"z":-0.15},
  HALF_EXTENT: {"x":19.03,"z":20.05},
};

// All twenty PlayerStarts, ten a side, sorted along x. Handed out round-robin. Each one
// is on a navmesh polygon, at that polygon's height plus the 0.05 lift.
const SPAWNS = {
  red: [
  {"x":93.97,"y":-0.36,"z":19.59,"ry":1.339,"ut":"PlayerStart0"},
  {"x":98.86,"y":-0.36,"z":22.49,"ry":1.579,"ut":"PlayerStart24"},
  {"x":99.96,"y":-0.36,"z":-36.27,"ry":1.579,"ut":"PlayerStart20"},
  {"x":102.94,"y":-0.36,"z":16.8,"ry":1.579,"ut":"PlayerStart23"},
  {"x":105.25,"y":-0.36,"z":-42.51,"ry":1.579,"ut":"PlayerStart21"},
  {"x":108.28,"y":-0.36,"z":20.99,"ry":1.579,"ut":"PlayerStart22"},
  {"x":109.34,"y":-0.36,"z":-37.72,"ry":1.579,"ut":"PlayerStart2"},
  {"x":110.25,"y":-0.36,"z":16.5,"ry":1.579,"ut":"PlayerStart12"},
  {"x":113.43,"y":-0.36,"z":-36.33,"ry":1.579,"ut":"PlayerStart19"},
  {"x":118.2,"y":-0.36,"z":-36.71,"ry":1.579,"ut":"PlayerStart18"},
  ],
  blue: [
  {"x":-93,"y":-0.16,"z":22.7,"ry":-1.433,"ut":"PlayerStart1"},
  {"x":-90.93,"y":-0.36,"z":-32.53,"ry":-1.433,"ut":"PlayerStart10"},
  {"x":-89.55,"y":-0.36,"z":-30.04,"ry":-1.433,"ut":"PlayerStart8"},
  {"x":-89.36,"y":-0.14,"z":21.03,"ry":-1.433,"ut":"PlayerStart9"},
  {"x":-88.72,"y":-0.36,"z":-36.05,"ry":-1.433,"ut":"PlayerStart11"},
  {"x":-83.27,"y":-0.36,"z":25.61,"ry":-1.433,"ut":"PlayerStart4"},
  {"x":-82.58,"y":-0.36,"z":22.03,"ry":-1.433,"ut":"PlayerStart7"},
  {"x":-81.91,"y":-0.36,"z":-33.02,"ry":-1.433,"ut":"PlayerStart13"},
  {"x":-80.52,"y":-0.36,"z":-36.78,"ry":-1.433,"ut":"PlayerStart6"},
  {"x":-77.84,"y":-0.17,"z":22.07,"ry":-1.433,"ut":"PlayerStart5"},
  ],
};

// Body Armor in the original; this game has no armour, so the two roof pedestals carry
// the second Enforcer instead. Same bargain either way: climb the tower, get the prize.
const BODY_ARMOR = [
  {"name":"armor3","x":-80.03,"y":72.06,"z":-1.59},
  {"name":"armor2","x":104.51,"y":72.06,"z":-12.55},
];

// The eight MedBoxes in the tower bases.
const MED_BOXES = [
  {"name":"MedBox5","x":-70.34,"y":0.59,"z":3.27},
  {"name":"MedBox4","x":-70.33,"y":0.59,"z":5.12},
  {"name":"MedBox7","x":-70.08,"y":0.59,"z":-14.74},
  {"name":"MedBox6","x":-70.07,"y":0.59,"z":-12.89},
  {"name":"MedBox2","x":95.85,"y":0.59,"z":-1.53},
  {"name":"MedBox3","x":95.9,"y":0.59,"z":0.62},
  {"name":"MedBox0","x":95.48,"y":0.59,"z":-20.68},
  {"name":"MedBox1","x":96.15,"y":0.59,"z":-17.49},
];

// The big HealthPack at the centre of the bridge, on the bridge deck (raw converted y,
// not surface-snapped — the bridge arches). Not placed in-game yet.
const HEALTH_PACK = [
  {"name":"HealthPack0","x":11.52,"y":13.13,"z":-9.17},
];

// Every pickup in the level, by Unreal class, y unsnapped. Reference material for
// whatever gets placed next — weapons, ammo, the UDamage on each ramp.
const UT_PICKUPS = {
  "BulletBox": [
    {"name":"BulletBox6","x":-78.95,"y":70.72,"z":-10.38},
    {"name":"BulletBox5","x":-77.79,"y":70.72,"z":-10.6},
    {"name":"BulletBox7","x":-76.26,"y":70.72,"z":-1.44},
    {"name":"BulletBox4","x":-62.45,"y":34.5,"z":-5.37},
    {"name":"BulletBox9","x":-62.3,"y":34.62,"z":-1.54},
    {"name":"BulletBox8","x":-62.15,"y":34.62,"z":-8.85},
    {"name":"BulletBox12","x":-60.85,"y":22.59,"z":-7.94},
    {"name":"BulletBox13","x":-60.81,"y":22.59,"z":-2.84},
    {"name":"BulletBox11","x":-58.92,"y":34.62,"z":-8.99},
    {"name":"BulletBox10","x":-58.62,"y":34.62,"z":-1.85},
    {"name":"BulletBox15","x":83.89,"y":35.18,"z":-12.84},
    {"name":"BulletBox0","x":85.04,"y":35.07,"z":-9.44},
    {"name":"BulletBox14","x":87.63,"y":35.18,"z":-12.76},
    {"name":"BulletBox16","x":87.66,"y":35.18,"z":-5.75},
    {"name":"BulletBox1","x":100.55,"y":71.28,"z":-12.92},
    {"name":"BulletBox2","x":104.41,"y":71.28,"z":-4.78},
    {"name":"BulletBox3","x":105.83,"y":71.28,"z":-4.91},
  ],
  "HealthPack": [
    {"name":"HealthPack0","x":11.52,"y":13.13,"z":-9.17},
  ],
  "MedBox": [
    {"name":"MedBox5","x":-70.34,"y":-1.52,"z":3.27},
    {"name":"MedBox4","x":-70.33,"y":-1.52,"z":5.12},
    {"name":"MedBox7","x":-70.08,"y":-1.52,"z":-14.74},
    {"name":"MedBox6","x":-70.07,"y":-1.52,"z":-12.89},
    {"name":"MedBox2","x":95.85,"y":-0.82,"z":-1.53},
    {"name":"MedBox3","x":95.9,"y":-0.82,"z":0.62},
    {"name":"MedBox0","x":96.08,"y":-0.79,"z":-19.64},
    {"name":"MedBox1","x":96.15,"y":-0.79,"z":-17.49},
  ],
  "RocketPack": [
    {"name":"RocketPack6","x":-86.46,"y":-1.29,"z":-11.02},
    {"name":"RocketPack7","x":-83.78,"y":-1.36,"z":-13.56},
    {"name":"RocketPack5","x":-68.22,"y":13.61,"z":-3.67},
    {"name":"RocketPack4","x":-68.11,"y":13.61,"z":-6.81},
    {"name":"RocketPack3","x":93.1,"y":14.17,"z":-11.45},
    {"name":"RocketPack2","x":93.15,"y":14.17,"z":-7.53},
    {"name":"RocketPack0","x":109.91,"y":-0.65,"z":-0.88},
    {"name":"RocketPack1","x":112.45,"y":-0.65,"z":-3.22},
  ],
  "ShockCore": [
    {"name":"ShockCore2","x":-76.84,"y":-1.19,"z":8.98},
    {"name":"ShockCore3","x":-73.8,"y":-1.19,"z":9},
    {"name":"ShockCore1","x":99.18,"y":-0.47,"z":-23.47},
    {"name":"ShockCore0","x":102.55,"y":-0.47,"z":-23.51},
  ],
  "ShockRifle": [
    {"name":"ShockRifle1","x":-75.31,"y":-1.52,"z":8.97},
    {"name":"ShockRifle0","x":100.91,"y":-0.79,"z":-23.55},
  ],
  "SniperRifle": [
    {"name":"SniperRifle5","x":-86.05,"y":-1.5,"z":14.54},
    {"name":"SniperRifle2","x":-71.36,"y":70.86,"z":-5.31},
    {"name":"SniperRifle3","x":-64.17,"y":34.81,"z":-6.64},
    {"name":"SniperRifle0","x":88.39,"y":35.56,"z":-8.17},
    {"name":"SniperRifle1","x":96.09,"y":71.56,"z":-9.31},
    {"name":"SniperRifle4","x":112.23,"y":-0.82,"z":10.4},
  ],
  "UDamage": [
    {"name":"UDamage3","x":-67.1,"y":14.03,"z":-5.32},
    {"name":"UDamage2","x":93.33,"y":15.11,"z":-9.53},
  ],
  "UT_Eightball": [
    {"name":"UT_Eightball3","x":-85.36,"y":-1.29,"z":-12.1},
    {"name":"UT_Eightball0","x":110.71,"y":-0.7,"z":-2.07},
  ],
  "WarheadLauncher": [
    {"name":"WarheadLauncher1","x":-56.78,"y":23.15,"z":-5.26},
    {"name":"WarheadLauncher2","x":82.49,"y":23.5,"z":-9.25},
  ],
  "armor2": [
    {"name":"armor3","x":-80.03,"y":71.19,"z":-1.59},
    {"name":"armor2","x":104.51,"y":71.77,"z":-12.55},
  ],
  "ripper": [
    {"name":"ripper1","x":-86.63,"y":-1.52,"z":-25.75},
    {"name":"ripper0","x":112.19,"y":-0.85,"z":-29.45},
  ],
};

module.exports = { GROUND_Y, FLAG_HOMES, TOWER_ROOFS, SPAWNS, BODY_ARMOR, MED_BOXES, HEALTH_PACK, UT_PICKUPS };
