// GENERATED by scripts/gen-nav-graph.mjs — DO NOT EDIT.
//
// CTF-Face's real path network — the graph UT99's own bots walk — converted from
// Unreal Units to this game's scene coordinates by src/shared/map-transform.js.
// Regenerate with:
//
//   node scripts/gen-nav-graph.mjs
//
// Source: scripts/data/ctf-face-nav.json.
//
// EDGES ARE EPIC'S OWN.
// Every edge is one non-pruned FReachSpec out of the TArray<FReachSpec> serialized
// inside the .unr's ULevel object: Epic's path compiler wrote them, and each carries
// its own direction, length and reach kind. The dump cross-checks the ReachSpec table
// against all 1184 Paths[]/upstreamPaths[] entries on the NavigationPoints
// themselves and every one agrees, so this is a verified decode rather than a
// plausible one. The 364 specs the compiler marked bPruned (redundant with a
// chain of others) are left out, exactly as UT's bots leave them out.
//
// NODES  166 NavigationPoints — 3 Ambushpoint, 9 DefensePoint, 2 FlagBase, 56 InventorySpot, 12 LiftExit, 47 PathNode, 20 PlayerStart, 12 Teleporter, 5 translocdest.
// EDGES  592, DIRECTED. Epic's graph is not symmetric: a drop you can fall down
//        but not climb back up is one spec, not two. Do not assume `to`/`from` reverse.
//
// COORDINATES are scene units, straight through uuToScene() with no navmesh snapping —
// the honest conversion of Epic's placement, good to roughly a unit indoors and better
// outdoors (see the residuals in src/shared/map-transform.js). Anything that has to
// stand exactly on a surface should snap its own y; a bot steering towards a waypoint
// does not need to. Mirrored from src/shared/map-transform.js at generation time, the
// way server/map-actors.js mirrors the actor table:
//
//   UU_TO_M = 0.023500002239999998
//   OFFSET  = (-51.3, 46.41, -5.3)
//   scene   = (UU_TO_M*uu.x + OFFSET.x, UU_TO_M*uu.z + OFFSET.y, UU_TO_M*uu.y + OFFSET.z)
//
// COSTS are Epic's own path length for the edge (`distance`, in UU) times UU_TO_M, so a
// cost is in the same units as the coordinates. UT truncates that length to an INT, so
// a walk spec can read up to 1 UU (0.024 units) shorter than the straight line between
// its endpoints; 513 of the 560 walk/jump edges did, and each was floored back up to it so
// the heuristic in aStar() stays admissible. R_SPECIAL edges are NOT floored: their
// `distance` is a flat nominal cost (a teleport is instantaneous, and the longest one
// here jumps 2882 UU for a stated 100), so aStar() drops to a zero heuristic — plain
// Dijkstra, still optimal — whenever it is allowed to use them.
//
// CONNECTIVITY, checked at generation time:
//   whole graph, every edge         one connected component (all 166 nodes)
//   walkable only (no R_SPECIAL)    13 components, sizes [115, 10, 10, 8, 7, 5, 4, 2, 1, 1, 1, 1, 1]
//
// That split is the map, not a bug: CTF-Face reaches its tower alcoves and its
// translocator pads through teleporters, and a teleporter traversal is an R_SPECIAL
// spec. This game has no teleporters and no translocator, so aStar() leaves R_SPECIAL
// edges out BY DEFAULT and the reachable world is the 115-node main component —
// which contains both flag bases and all 20 player starts, verified below. Pass
// { special: true } to get Epic's full, single-component graph back.
//
// The 12 pockets that fall off without R_SPECIAL:
//   10: LiftExit6, InventorySpot137, InventorySpot136, PathNode59, InventorySpot139, InventorySpot138, Teleporter9, InventorySpot132, DefensePoint9, DefensePoint8
//   10: PathNode18, InventorySpot131, PathNode57, InventorySpot130, InventorySpot127, DefensePoint10, InventorySpot129, InventorySpot128, Teleporter11, DefensePoint11
//   8: Teleporter7, InventorySpot135, InventorySpot160, InventorySpot161, InventorySpot159, InventorySpot162, InventorySpot133, DefensePoint14
//   7: Teleporter1, InventorySpot167, InventorySpot165, InventorySpot166, InventorySpot125, InventorySpot124, DefensePoint13
//   5: LiftExit1, InventorySpot152, InventorySpot142, InventorySpot141, LiftExit0
//   4: Teleporter4, InventorySpot164, InventorySpot163, InventorySpot153
//   2: Teleporter2, InventorySpot154
//   1: translocdest3
//   1: translocdest2
//   1: translocdest1
//   1: translocdest4
//   1: translocdest0
//
// SANITY, asserted by the generator before this file is written: every FlagBase and
// every PlayerStart in src/shared/map-actors.js has a nav node within 8 scene units
// (worst: 1.66), and that node is in the main walkable component.

// The UE1 reachFlags bitfield, verbatim. `flags` on every edge is one of these ORed.
const REACH_FLAGS = { WALK: 1, FLY: 2, SWIM: 4, JUMP: 8, DOOR: 16, SPECIAL: 32, PLAYER_ONLY: 64 };

// id is the index into this array, so NODES[i].id === i.
const NODES = [
  {"id":0,"cls":"LiftExit","name":"LiftExit8","x":-23.4,"y":11.05,"z":7.78},
  {"id":1,"cls":"LiftExit","name":"LiftExit4","x":-43.43,"y":3.95,"z":-1.02},
  {"id":2,"cls":"InventorySpot","name":"InventorySpot145","x":-76.84,"y":-0.45,"z":8.98},
  {"id":3,"cls":"PathNode","name":"PathNode38","x":94.54,"y":0.4,"z":-9.11},
  {"id":4,"cls":"LiftExit","name":"LiftExit11","x":64.67,"y":5.57,"z":-18.06},
  {"id":5,"cls":"DefensePoint","name":"DefensePoint2","x":-71.66,"y":-0.51,"z":0.4,"team":"blue"},
  {"id":6,"cls":"InventorySpot","name":"InventorySpot113","x":100.91,"y":0.23,"z":-23.55},
  {"id":7,"cls":"PathNode","name":"PathNode8","x":42.98,"y":6.15,"z":5.6},
  {"id":8,"cls":"InventorySpot","name":"InventorySpot112","x":110.29,"y":0.23,"z":-2.5},
  {"id":9,"cls":"InventorySpot","name":"InventorySpot117","x":102.55,"y":0.23,"z":-23.51},
  {"id":10,"cls":"InventorySpot","name":"InventorySpot150","x":-70.64,"y":-0.45,"z":-14.74},
  {"id":11,"cls":"InventorySpot","name":"InventorySpot147","x":-75.31,"y":-0.45,"z":8.97},
  {"id":12,"cls":"InventorySpot","name":"InventorySpot121","x":96.26,"y":0.23,"z":0.62},
  {"id":13,"cls":"PathNode","name":"PathNode25","x":-68.75,"y":-0.16,"z":-5.24},
  {"id":14,"cls":"LiftExit","name":"LiftExit6","x":-70.09,"y":71.66,"z":-4.27},
  {"id":15,"cls":"InventorySpot","name":"InventorySpot134","x":-70.64,"y":-0.47,"z":4.97},
  {"id":16,"cls":"InventorySpot","name":"InventorySpot132","x":-71.36,"y":71.72,"z":-5.31},
  {"id":17,"cls":"InventorySpot","name":"InventorySpot116","x":112.45,"y":0,"z":-3.22},
  {"id":18,"cls":"InventorySpot","name":"InventorySpot146","x":-73.8,"y":-0.45,"z":9},
  {"id":19,"cls":"InventorySpot","name":"InventorySpot148","x":-70.64,"y":-0.45,"z":3.27},
  {"id":20,"cls":"PathNode","name":"PathNode35","x":-81.69,"y":-0.54,"z":1.52},
  {"id":21,"cls":"InventorySpot","name":"InventorySpot114","x":96.26,"y":0.21,"z":-19.52},
  {"id":22,"cls":"DefensePoint","name":"DefensePoint1","x":-72.57,"y":-0.51,"z":-17.94,"team":"blue"},
  {"id":23,"cls":"InventorySpot","name":"InventorySpot149","x":-70.64,"y":-0.45,"z":-12.89},
  {"id":24,"cls":"InventorySpot","name":"InventorySpot120","x":96.26,"y":0.23,"z":-1.53},
  {"id":25,"cls":"PathNode","name":"PathNode34","x":105.35,"y":0.03,"z":-16.88},
  {"id":26,"cls":"Ambushpoint","name":"Ambushpoint3","x":99.66,"y":0.03,"z":2.62},
  {"id":27,"cls":"InventorySpot","name":"InventorySpot140","x":-85,"y":-0.45,"z":-11.75},
  {"id":28,"cls":"InventorySpot","name":"InventorySpot119","x":96.26,"y":0.23,"z":-17.49},
  {"id":29,"cls":"PathNode","name":"PathNode55","x":106.74,"y":0.17,"z":-9.29},
  {"id":30,"cls":"LiftExit","name":"LiftExit3","x":75.4,"y":0.07,"z":-12.54},
  {"id":31,"cls":"Ambushpoint","name":"Ambushpoint5","x":103.89,"y":0.03,"z":1.99},
  {"id":32,"cls":"InventorySpot","name":"InventorySpot115","x":109.14,"y":0.23,"z":-0.88},
  {"id":33,"cls":"InventorySpot","name":"InventorySpot118","x":99.18,"y":0.23,"z":-23.47},
  {"id":34,"cls":"Ambushpoint","name":"Ambushpoint4","x":102.07,"y":0.03,"z":-0.48},
  {"id":35,"cls":"PathNode","name":"PathNode54","x":-80.47,"y":-0.51,"z":-5.26},
  {"id":36,"cls":"PlayerStart","name":"PlayerStart4","x":-83.27,"y":-0.47,"z":25.61,"team":"blue"},
  {"id":37,"cls":"PathNode","name":"PathNode18","x":96.56,"y":72.22,"z":-6.55},
  {"id":38,"cls":"LiftExit","name":"LiftExit9","x":-52.69,"y":-0.16,"z":-5.44},
  {"id":39,"cls":"DefensePoint","name":"DefensePoint8","x":-70.11,"y":71.66,"z":-2.18,"team":"blue"},
  {"id":40,"cls":"InventorySpot","name":"InventorySpot143","x":-86.46,"y":-0.63,"z":-11.02},
  {"id":41,"cls":"InventorySpot","name":"InventorySpot131","x":96.09,"y":72.29,"z":-9.31},
  {"id":42,"cls":"PlayerStart","name":"PlayerStart12","x":110.25,"y":0.03,"z":16.5,"team":"red"},
  {"id":43,"cls":"PlayerStart","name":"PlayerStart9","x":-89.36,"y":-0.47,"z":21.03,"team":"blue"},
  {"id":44,"cls":"InventorySpot","name":"InventorySpot127","x":100.55,"y":72.29,"z":-12.92},
  {"id":45,"cls":"LiftExit","name":"LiftExit7","x":-31.97,"y":0.61,"z":4.32},
  {"id":46,"cls":"FlagBase","name":"FlagBase0","x":101.18,"y":0.43,"z":5,"team":"red"},
  {"id":47,"cls":"PlayerStart","name":"PlayerStart5","x":-78.03,"y":-0.47,"z":22.79,"team":"blue"},
  {"id":48,"cls":"FlagBase","name":"FlagBase1","x":-75.11,"y":0.14,"z":-19.22,"team":"blue"},
  {"id":49,"cls":"PathNode","name":"PathNode39","x":121.28,"y":0.16,"z":-33.48},
  {"id":50,"cls":"InventorySpot","name":"InventorySpot130","x":104.51,"y":72.29,"z":-12.55},
  {"id":51,"cls":"PathNode","name":"PathNode57","x":104.99,"y":72.22,"z":-13.36},
  {"id":52,"cls":"PlayerStart","name":"PlayerStart2","x":109.34,"y":-0.21,"z":-37.72,"team":"red"},
  {"id":53,"cls":"InventorySpot","name":"InventorySpot144","x":-83.78,"y":-0.45,"z":-13.56},
  {"id":54,"cls":"PathNode","name":"PathNode43","x":-92.33,"y":-0.51,"z":18.96},
  {"id":55,"cls":"PathNode","name":"PathNode14","x":41.32,"y":5.98,"z":-24.26},
  {"id":56,"cls":"PathNode","name":"PathNode27","x":-44.9,"y":-0.38,"z":5.4},
  {"id":57,"cls":"PathNode","name":"PathNode2","x":-25.66,"y":3.24,"z":3.59},
  {"id":58,"cls":"Teleporter","name":"Teleporter1","x":90.26,"y":35.89,"z":-9.33},
  {"id":59,"cls":"PathNode","name":"PathNode23","x":-42.19,"y":-0.51,"z":-15.53},
  {"id":60,"cls":"PathNode","name":"PathNode0","x":-48.64,"y":-0.16,"z":-5.37},
  {"id":61,"cls":"DefensePoint","name":"DefensePoint11","x":95.87,"y":72.22,"z":-5.28},
  {"id":62,"cls":"PlayerStart","name":"PlayerStart18","x":118.2,"y":-0.21,"z":-36.71,"team":"red"},
  {"id":63,"cls":"PlayerStart","name":"PlayerStart22","x":108.28,"y":0.03,"z":20.99,"team":"red"},
  {"id":64,"cls":"Teleporter","name":"Teleporter0","x":106.15,"y":0.31,"z":-24.26},
  {"id":65,"cls":"InventorySpot","name":"InventorySpot138","x":-76.26,"y":71.72,"z":-1.44},
  {"id":66,"cls":"Teleporter","name":"Teleporter6","x":-80.52,"y":-0.51,"z":9.61},
  {"id":67,"cls":"PlayerStart","name":"PlayerStart6","x":-80.52,"y":-0.47,"z":-36.78,"team":"blue"},
  {"id":68,"cls":"Teleporter","name":"Teleporter11","x":103.44,"y":69.73,"z":-9.1},
  {"id":69,"cls":"PlayerStart","name":"PlayerStart13","x":-81.91,"y":-0.47,"z":-33.02,"team":"blue"},
  {"id":70,"cls":"PlayerStart","name":"PlayerStart1","x":-93,"y":-0.47,"z":22.7,"team":"blue"},
  {"id":71,"cls":"PlayerStart","name":"PlayerStart8","x":-89.55,"y":-0.47,"z":-30.04,"team":"blue"},
  {"id":72,"cls":"PlayerStart","name":"PlayerStart7","x":-81.41,"y":-0.47,"z":20.86,"team":"blue"},
  {"id":73,"cls":"LiftExit","name":"LiftExit5","x":51.79,"y":2.5,"z":-24.51},
  {"id":74,"cls":"InventorySpot","name":"InventorySpot129","x":105.83,"y":72.29,"z":-4.91},
  {"id":75,"cls":"PathNode","name":"PathNode30","x":112.05,"y":0.17,"z":19.35},
  {"id":76,"cls":"PathNode","name":"PathNode13","x":49.94,"y":3.3,"z":-20.72},
  {"id":77,"cls":"PlayerStart","name":"PlayerStart0","x":93.97,"y":0.03,"z":19.59,"team":"red"},
  {"id":78,"cls":"DefensePoint","name":"DefensePoint10","x":95.63,"y":72.22,"z":-13.8},
  {"id":79,"cls":"InventorySpot","name":"InventorySpot139","x":-80.03,"y":71.72,"z":-1.59},
  {"id":80,"cls":"PlayerStart","name":"PlayerStart20","x":100.08,"y":-0.21,"z":-35.84,"team":"red"},
  {"id":81,"cls":"PathNode","name":"PathNode12","x":59.77,"y":0.54,"z":-16.13},
  {"id":82,"cls":"PlayerStart","name":"PlayerStart19","x":113.43,"y":-0.21,"z":-36.33,"team":"red"},
  {"id":83,"cls":"Teleporter","name":"Teleporter7","x":-65.14,"y":35.49,"z":-5.19},
  {"id":84,"cls":"DefensePoint","name":"DefensePoint0","x":-78.56,"y":-0.51,"z":-17.43,"team":"blue"},
  {"id":85,"cls":"Teleporter","name":"Teleporter5","x":-70.07,"y":-0.47,"z":9.74},
  {"id":86,"cls":"LiftExit","name":"LiftExit10","x":84.92,"y":15.07,"z":-8.37},
  {"id":87,"cls":"Teleporter","name":"Teleporter3","x":95.75,"y":-0.21,"z":-24.26},
  {"id":88,"cls":"InventorySpot","name":"InventorySpot126","x":11.43,"y":14.13,"z":-9.15},
  {"id":89,"cls":"PathNode","name":"PathNode46","x":-94.64,"y":-0.51,"z":-26.22},
  {"id":90,"cls":"PathNode","name":"PathNode21","x":-23.48,"y":5.42,"z":-22.9},
  {"id":91,"cls":"PathNode","name":"PathNode5","x":9.9,"y":13.68,"z":-2},
  {"id":92,"cls":"PathNode","name":"PathNode1","x":-36.22,"y":-0.71,"z":-0.7},
  {"id":93,"cls":"Teleporter","name":"Teleporter9","x":-79.16,"y":69.33,"z":-5.23},
  {"id":94,"cls":"InventorySpot","name":"InventorySpot128","x":104.41,"y":72.29,"z":-4.78},
  {"id":95,"cls":"PathNode","name":"PathNode10","x":62.55,"y":0.39,"z":2.05},
  {"id":96,"cls":"PlayerStart","name":"PlayerStart21","x":105.25,"y":-0.21,"z":-42.51,"team":"red"},
  {"id":97,"cls":"LiftExit","name":"LiftExit1","x":-60.16,"y":14.5,"z":-4.83},
  {"id":98,"cls":"PathNode","name":"PathNode59","x":-81.16,"y":71.66,"z":-5.58},
  {"id":99,"cls":"PlayerStart","name":"PlayerStart10","x":-90.93,"y":-0.47,"z":-32.53,"team":"blue"},
  {"id":100,"cls":"InventorySpot","name":"InventorySpot159","x":-62.15,"y":35.32,"z":-8.85},
  {"id":101,"cls":"InventorySpot","name":"InventorySpot135","x":-62.45,"y":35.21,"z":-5.37},
  {"id":102,"cls":"PlayerStart","name":"PlayerStart11","x":-88.72,"y":-0.47,"z":-36.05,"team":"blue"},
  {"id":103,"cls":"LiftExit","name":"LiftExit2","x":85.39,"y":15.04,"z":-9.71},
  {"id":104,"cls":"PathNode","name":"PathNode15","x":34.74,"y":8.38,"z":-23.89},
  {"id":105,"cls":"LiftExit","name":"LiftExit0","x":-60.16,"y":14.5,"z":-5.56},
  {"id":106,"cls":"InventorySpot","name":"InventorySpot136","x":-77.79,"y":71.72,"z":-10.6},
  {"id":107,"cls":"PathNode","name":"PathNode16","x":25.82,"y":10.81,"z":-18.43},
  {"id":108,"cls":"PathNode","name":"PathNode6","x":13.64,"y":14.03,"z":-1.64},
  {"id":109,"cls":"PathNode","name":"PathNode17","x":11.76,"y":14.24,"z":-11.19},
  {"id":110,"cls":"PlayerStart","name":"PlayerStart24","x":98.86,"y":0.03,"z":22.49,"team":"red"},
  {"id":111,"cls":"PlayerStart","name":"PlayerStart23","x":102.94,"y":0.03,"z":16.8,"team":"red"},
  {"id":112,"cls":"InventorySpot","name":"InventorySpot152","x":-67.1,"y":14.57,"z":-5.32},
  {"id":113,"cls":"InventorySpot","name":"InventorySpot137","x":-78.95,"y":71.72,"z":-10.38},
  {"id":114,"cls":"Teleporter","name":"Teleporter4","x":-60.92,"y":23.32,"z":-5.22},
  {"id":115,"cls":"PathNode","name":"PathNode22","x":-33.3,"y":1.85,"z":-19.74},
  {"id":116,"cls":"PathNode","name":"PathNode7","x":32.55,"y":8.7,"z":4.84},
  {"id":117,"cls":"PathNode","name":"PathNode9","x":53,"y":2.71,"z":4.4},
  {"id":118,"cls":"PathNode","name":"PathNode3","x":-14.46,"y":7.92,"z":7.29},
  {"id":119,"cls":"PathNode","name":"PathNode28","x":74.34,"y":0.17,"z":-22.35},
  {"id":120,"cls":"PathNode","name":"PathNode45","x":-96.24,"y":-0.51,"z":12.48},
  {"id":121,"cls":"InventorySpot","name":"InventorySpot125","x":88.39,"y":36.19,"z":-8.17},
  {"id":122,"cls":"InventorySpot","name":"InventorySpot133","x":-64.17,"y":35.63,"z":-6.64},
  {"id":123,"cls":"PathNode","name":"PathNode36","x":119.48,"y":0.17,"z":10.03},
  {"id":124,"cls":"PathNode","name":"PathNode20","x":-14.15,"y":8.24,"z":-24.02},
  {"id":125,"cls":"InventorySpot","name":"InventorySpot160","x":-62.3,"y":35.32,"z":-1.54},
  {"id":126,"cls":"InventorySpot","name":"InventorySpot165","x":87.63,"y":35.89,"z":-12.76},
  {"id":127,"cls":"PathNode","name":"PathNode24","x":-65.57,"y":-0.43,"z":23.41},
  {"id":128,"cls":"PathNode","name":"PathNode41","x":86.32,"y":0.17,"z":-34.37},
  {"id":129,"cls":"InventorySpot","name":"InventorySpot151","x":93.33,"y":15.11,"z":-9.53},
  {"id":130,"cls":"InventorySpot","name":"InventorySpot155","x":112.23,"y":0.23,"z":10.4},
  {"id":131,"cls":"InventorySpot","name":"InventorySpot141","x":-68.11,"y":14.57,"z":-6.81},
  {"id":132,"cls":"InventorySpot","name":"InventorySpot156","x":112.19,"y":0.23,"z":-29.45},
  {"id":133,"cls":"InventorySpot","name":"InventorySpot122","x":93.15,"y":15.14,"z":-7.53},
  {"id":134,"cls":"InventorySpot","name":"InventorySpot158","x":-86.05,"y":-0.45,"z":14.54},
  {"id":135,"cls":"InventorySpot","name":"InventorySpot142","x":-68.22,"y":14.57,"z":-3.67},
  {"id":136,"cls":"DefensePoint","name":"DefensePoint9","x":-70.53,"y":71.66,"z":-10.12,"team":"blue"},
  {"id":137,"cls":"InventorySpot","name":"InventorySpot123","x":92.7,"y":15.14,"z":-11.05},
  {"id":138,"cls":"InventorySpot","name":"InventorySpot157","x":-86.63,"y":-0.45,"z":-25.75},
  {"id":139,"cls":"PathNode","name":"PathNode4","x":-1.02,"y":11.09,"z":4.05},
  {"id":140,"cls":"PathNode","name":"PathNode37","x":82.86,"y":0.4,"z":-8.9},
  {"id":141,"cls":"PathNode","name":"PathNode19","x":-3.29,"y":11.34,"z":-18.46},
  {"id":142,"cls":"InventorySpot","name":"InventorySpot124","x":85.04,"y":35.77,"z":-9.44},
  {"id":143,"cls":"PathNode","name":"PathNode26","x":-55.15,"y":-0.41,"z":17.75},
  {"id":144,"cls":"PathNode","name":"PathNode48","x":-64.73,"y":-0.51,"z":-33.86},
  {"id":145,"cls":"PathNode","name":"PathNode33","x":76.18,"y":-0.01,"z":7.74},
  {"id":146,"cls":"PathNode","name":"PathNode29","x":-53.43,"y":-0.25,"z":-23.76},
  {"id":147,"cls":"InventorySpot","name":"InventorySpot167","x":87.66,"y":35.89,"z":-5.75},
  {"id":148,"cls":"InventorySpot","name":"InventorySpot153","x":-56.78,"y":23.6,"z":-5.26},
  {"id":149,"cls":"InventorySpot","name":"InventorySpot163","x":-60.85,"y":23.54,"z":-7.29},
  {"id":150,"cls":"InventorySpot","name":"InventorySpot164","x":-60.81,"y":23.55,"z":-3.2},
  {"id":151,"cls":"translocdest","name":"translocdest3","x":-24.02,"y":11.15,"z":7.72},
  {"id":152,"cls":"translocdest","name":"translocdest2","x":-44.21,"y":3.93,"z":-1.23},
  {"id":153,"cls":"PathNode","name":"PathNode49","x":121.66,"y":0.16,"z":-22.27},
  {"id":154,"cls":"Teleporter","name":"Teleporter2","x":86.28,"y":24.16,"z":-9.27},
  {"id":155,"cls":"translocdest","name":"translocdest1","x":84.73,"y":15.07,"z":-9.72},
  {"id":156,"cls":"Teleporter","name":"Teleporter10","x":99.84,"y":0.31,"z":-9.3},
  {"id":157,"cls":"DefensePoint","name":"DefensePoint14","x":-58.25,"y":35.78,"z":-5.3,"team":"blue"},
  {"id":158,"cls":"DefensePoint","name":"DefensePoint13","x":84.02,"y":36.12,"z":-9.21},
  {"id":159,"cls":"translocdest","name":"translocdest4","x":65.12,"y":5.57,"z":-17.95},
  {"id":160,"cls":"Teleporter","name":"Teleporter8","x":-74.67,"y":-0.61,"z":-5.26},
  {"id":161,"cls":"translocdest","name":"translocdest0","x":-59.05,"y":14.5,"z":-5.55},
  {"id":162,"cls":"InventorySpot","name":"InventorySpot162","x":-58.92,"y":35.32,"z":-8.99},
  {"id":163,"cls":"InventorySpot","name":"InventorySpot154","x":82.49,"y":24.16,"z":-9.25},
  {"id":164,"cls":"InventorySpot","name":"InventorySpot161","x":-58.62,"y":35.32,"z":-1.85},
  {"id":165,"cls":"InventorySpot","name":"InventorySpot166","x":83.89,"y":35.89,"z":-12.84},
];

// Directed. `cost` is Epic's path length in scene units.
const EDGES = [
  {"from":52,"to":82,"cost":4.32,"flags":1},
  {"from":52,"to":80,"cost":9.45,"flags":1},
  {"from":52,"to":96,"cost":6.3,"flags":1},
  {"from":52,"to":132,"cost":8.76,"flags":9},
  {"from":60,"to":92,"cost":13.28,"flags":1},
  {"from":60,"to":59,"cost":12.04,"flags":1},
  {"from":60,"to":56,"cost":11.4,"flags":1},
  {"from":60,"to":38,"cost":4.05,"flags":1},
  {"from":92,"to":60,"cost":13.28,"flags":1},
  {"from":92,"to":56,"cost":10.61,"flags":1},
  {"from":92,"to":45,"cost":6.71,"flags":1},
  {"from":57,"to":118,"cost":12.69,"flags":1},
  {"from":57,"to":45,"cost":6.88,"flags":1},
  {"from":118,"to":57,"cost":12.69,"flags":1},
  {"from":118,"to":139,"cost":14.18,"flags":1},
  {"from":139,"to":118,"cost":14.18,"flags":1},
  {"from":139,"to":91,"cost":12.75,"flags":1},
  {"from":91,"to":139,"cost":12.75,"flags":1},
  {"from":91,"to":108,"cost":3.77,"flags":1},
  {"from":91,"to":88,"cost":7.33,"flags":1},
  {"from":108,"to":91,"cost":3.77,"flags":1},
  {"from":108,"to":116,"cost":20.69,"flags":1},
  {"from":108,"to":88,"cost":7.83,"flags":1},
  {"from":116,"to":108,"cost":20.69,"flags":1},
  {"from":116,"to":117,"cost":21.31,"flags":1},
  {"from":7,"to":116,"cost":10.76,"flags":1},
  {"from":7,"to":117,"cost":10.66,"flags":1},
  {"from":117,"to":116,"cost":21.31,"flags":1},
  {"from":117,"to":95,"cost":10.11,"flags":1},
  {"from":95,"to":117,"cost":10.11,"flags":1},
  {"from":95,"to":140,"cost":23.08,"flags":1},
  {"from":95,"to":145,"cost":14.78,"flags":1},
  {"from":95,"to":30,"cost":19.44,"flags":1},
  {"from":81,"to":76,"cost":11.19,"flags":1},
  {"from":81,"to":119,"cost":15.85,"flags":1},
  {"from":81,"to":30,"cost":16.05,"flags":1},
  {"from":81,"to":73,"cost":11.74,"flags":1},
  {"from":76,"to":81,"cost":11.19,"flags":1},
  {"from":76,"to":55,"cost":9.7,"flags":1},
  {"from":76,"to":73,"cost":4.29,"flags":1},
  {"from":55,"to":76,"cost":9.7,"flags":1},
  {"from":55,"to":104,"cost":7.01,"flags":1},
  {"from":55,"to":73,"cost":11.04,"flags":1},
  {"from":104,"to":55,"cost":7.01,"flags":1},
  {"from":104,"to":107,"cost":10.74,"flags":1},
  {"from":107,"to":104,"cost":10.74,"flags":1},
  {"from":107,"to":109,"cost":16.18,"flags":1},
  {"from":109,"to":107,"cost":16.18,"flags":1},
  {"from":109,"to":88,"cost":2.07,"flags":1},
  {"from":141,"to":124,"cost":12.59,"flags":1},
  {"from":141,"to":88,"cost":17.64,"flags":1},
  {"from":124,"to":141,"cost":12.59,"flags":1},
  {"from":124,"to":90,"cost":9.81,"flags":1},
  {"from":90,"to":124,"cost":9.81,"flags":1},
  {"from":90,"to":115,"cost":10.92,"flags":1},
  {"from":115,"to":90,"cost":10.92,"flags":1},
  {"from":115,"to":59,"cost":10.12,"flags":1},
  {"from":59,"to":60,"cost":12.04,"flags":1},
  {"from":59,"to":115,"cost":10.12,"flags":1},
  {"from":59,"to":146,"cost":13.93,"flags":1},
  {"from":13,"to":48,"cost":15.36,"flags":1},
  {"from":13,"to":38,"cost":16.06,"flags":1},
  {"from":13,"to":22,"cost":13.27,"flags":1},
  {"from":13,"to":5,"cost":6.36,"flags":1},
  {"from":13,"to":11,"cost":15.65,"flags":9},
  {"from":13,"to":23,"cost":7.89,"flags":1},
  {"from":140,"to":95,"cost":23.08,"flags":1},
  {"from":140,"to":3,"cost":11.68,"flags":1},
  {"from":140,"to":30,"cost":8.31,"flags":1},
  {"from":3,"to":140,"cost":11.68,"flags":1},
  {"from":3,"to":26,"cost":12.8,"flags":9},
  {"from":3,"to":6,"cost":15.78,"flags":1},
  {"from":3,"to":28,"cost":8.56,"flags":1},
  {"from":3,"to":24,"cost":7.78,"flags":1},
  {"from":46,"to":26,"cost":2.85,"flags":1},
  {"from":46,"to":34,"cost":5.57,"flags":1},
  {"from":46,"to":31,"cost":4.07,"flags":1},
  {"from":48,"to":13,"cost":15.36,"flags":1},
  {"from":48,"to":84,"cost":3.94,"flags":1},
  {"from":48,"to":22,"cost":2.92,"flags":1},
  {"from":48,"to":27,"cost":12.41,"flags":1},
  {"from":48,"to":40,"cost":14.02,"flags":1},
  {"from":48,"to":53,"cost":10.37,"flags":1},
  {"from":48,"to":23,"cost":7.77,"flags":1},
  {"from":48,"to":10,"cost":6.36,"flags":1},
  {"from":43,"to":54,"cost":3.62,"flags":1},
  {"from":43,"to":70,"cost":4,"flags":1},
  {"from":43,"to":36,"cost":7.62,"flags":1},
  {"from":43,"to":72,"cost":7.95,"flags":1},
  {"from":43,"to":134,"cost":7.29,"flags":1},
  {"from":143,"to":56,"cost":16.05,"flags":1},
  {"from":143,"to":127,"cost":11.86,"flags":1},
  {"from":56,"to":60,"cost":11.4,"flags":1},
  {"from":56,"to":92,"cost":10.61,"flags":1},
  {"from":56,"to":143,"cost":16.05,"flags":1},
  {"from":56,"to":45,"cost":13.01,"flags":1},
  {"from":119,"to":81,"cost":15.85,"flags":1},
  {"from":119,"to":128,"cost":16.97,"flags":1},
  {"from":119,"to":30,"cost":9.87,"flags":9},
  {"from":119,"to":73,"cost":22.77,"flags":1},
  {"from":99,"to":89,"cost":7.32,"flags":1},
  {"from":99,"to":71,"cost":2.85,"flags":1},
  {"from":99,"to":102,"cost":4.16,"flags":1},
  {"from":99,"to":69,"cost":9.03,"flags":1},
  {"from":146,"to":59,"cost":13.93,"flags":1},
  {"from":146,"to":144,"cost":15.16,"flags":1},
  {"from":42,"to":75,"cost":3.37,"flags":1},
  {"from":42,"to":123,"cost":11.27,"flags":1},
  {"from":42,"to":63,"cost":4.9,"flags":1},
  {"from":42,"to":111,"cost":7.32,"flags":1},
  {"from":42,"to":130,"cost":6.42,"flags":1},
  {"from":145,"to":95,"cost":14.78,"flags":1},
  {"from":145,"to":77,"cost":21.38,"flags":1},
  {"from":145,"to":30,"cost":20.3,"flags":1},
  {"from":25,"to":29,"cost":7.72,"flags":1},
  {"from":25,"to":8,"cost":15.21,"flags":1},
  {"from":25,"to":6,"cost":8.02,"flags":1},
  {"from":25,"to":21,"cost":9.47,"flags":1},
  {"from":25,"to":32,"cost":16.44,"flags":1},
  {"from":25,"to":9,"cost":7.2,"flags":1},
  {"from":20,"to":35,"cost":6.89,"flags":1},
  {"from":20,"to":15,"cost":11.58,"flags":1},
  {"from":20,"to":2,"cost":8.9,"flags":1},
  {"from":20,"to":18,"cost":10.87,"flags":1},
  {"from":20,"to":11,"cost":9.81,"flags":1},
  {"from":26,"to":3,"cost":12.8,"flags":9},
  {"from":26,"to":46,"cost":2.85,"flags":1},
  {"from":26,"to":34,"cost":3.93,"flags":1},
  {"from":26,"to":31,"cost":4.28,"flags":1},
  {"from":26,"to":8,"cost":11.8,"flags":1},
  {"from":26,"to":32,"cost":10.11,"flags":1},
  {"from":26,"to":24,"cost":5.37,"flags":1},
  {"from":26,"to":12,"cost":3.95,"flags":1},
  {"from":34,"to":46,"cost":5.57,"flags":1},
  {"from":34,"to":26,"cost":3.93,"flags":1},
  {"from":34,"to":31,"cost":3.07,"flags":1},
  {"from":34,"to":32,"cost":7.08,"flags":1},
  {"from":34,"to":17,"cost":10.74,"flags":1},
  {"from":34,"to":24,"cost":5.91,"flags":1},
  {"from":34,"to":12,"cost":5.92,"flags":1},
  {"from":31,"to":46,"cost":4.07,"flags":1},
  {"from":31,"to":26,"cost":4.28,"flags":1},
  {"from":31,"to":34,"cost":3.07,"flags":1},
  {"from":31,"to":29,"cost":11.64,"flags":1},
  {"from":31,"to":8,"cost":7.82,"flags":1},
  {"from":31,"to":32,"cost":5.99,"flags":1},
  {"from":31,"to":17,"cost":10.02,"flags":1},
  {"from":77,"to":145,"cost":21.38,"flags":1},
  {"from":77,"to":111,"cost":9.4,"flags":1},
  {"from":77,"to":110,"cost":5.69,"flags":1},
  {"from":75,"to":42,"cost":3.37,"flags":1},
  {"from":75,"to":123,"cost":11.92,"flags":1},
  {"from":75,"to":63,"cost":4.11,"flags":1},
  {"from":75,"to":130,"cost":8.95,"flags":1},
  {"from":123,"to":42,"cost":11.27,"flags":9},
  {"from":123,"to":75,"cost":11.92,"flags":1},
  {"from":123,"to":130,"cost":7.26,"flags":1},
  {"from":49,"to":153,"cost":11.22,"flags":1},
  {"from":49,"to":62,"cost":4.48,"flags":1},
  {"from":49,"to":132,"cost":9.94,"flags":1},
  {"from":128,"to":119,"cost":16.97,"flags":1},
  {"from":128,"to":80,"cost":13.84,"flags":1},
  {"from":54,"to":43,"cost":3.62,"flags":1},
  {"from":54,"to":120,"cost":7.57,"flags":1},
  {"from":54,"to":70,"cost":3.8,"flags":1},
  {"from":54,"to":134,"cost":7.68,"flags":1},
  {"from":120,"to":54,"cost":7.57,"flags":1},
  {"from":89,"to":99,"cost":7.32,"flags":1},
  {"from":89,"to":71,"cost":6.36,"flags":1},
  {"from":89,"to":138,"cost":8.02,"flags":1},
  {"from":67,"to":144,"cost":16.06,"flags":1},
  {"from":67,"to":102,"cost":8.23,"flags":1},
  {"from":67,"to":69,"cost":4.01,"flags":1},
  {"from":144,"to":146,"cost":15.16,"flags":1},
  {"from":144,"to":67,"cost":16.06,"flags":1},
  {"from":153,"to":49,"cost":11.22,"flags":1},
  {"from":161,"to":105,"cost":11.75,"flags":32},
  {"from":105,"to":161,"cost":11.75,"flags":32},
  {"from":161,"to":38,"cost":11.75,"flags":32},
  {"from":38,"to":161,"cost":11.75,"flags":32},
  {"from":105,"to":97,"cost":0.73,"flags":1},
  {"from":103,"to":86,"cost":1.42,"flags":1},
  {"from":103,"to":133,"cost":8.06,"flags":1},
  {"from":103,"to":137,"cost":7.43,"flags":1},
  {"from":103,"to":129,"cost":7.94,"flags":1},
  {"from":30,"to":95,"cost":19.44,"flags":1},
  {"from":30,"to":81,"cost":16.05,"flags":1},
  {"from":30,"to":140,"cost":8.31,"flags":1},
  {"from":30,"to":119,"cost":9.87,"flags":1},
  {"from":30,"to":145,"cost":20.3,"flags":9},
  {"from":155,"to":103,"cost":11.75,"flags":32},
  {"from":103,"to":155,"cost":11.75,"flags":32},
  {"from":155,"to":30,"cost":11.75,"flags":32},
  {"from":30,"to":155,"cost":11.75,"flags":32},
  {"from":73,"to":81,"cost":11.74,"flags":1},
  {"from":73,"to":76,"cost":4.29,"flags":1},
  {"from":73,"to":55,"cost":11.04,"flags":1},
  {"from":73,"to":119,"cost":22.77,"flags":1},
  {"from":45,"to":92,"cost":6.71,"flags":1},
  {"from":45,"to":57,"cost":6.88,"flags":1},
  {"from":45,"to":56,"cost":13.01,"flags":1},
  {"from":70,"to":43,"cost":4,"flags":1},
  {"from":70,"to":54,"cost":3.8,"flags":1},
  {"from":36,"to":43,"cost":7.62,"flags":1},
  {"from":36,"to":47,"cost":5.95,"flags":1},
  {"from":36,"to":72,"cost":5.1,"flags":1},
  {"from":36,"to":134,"cost":11.41,"flags":9},
  {"from":47,"to":36,"cost":5.95,"flags":1},
  {"from":47,"to":72,"cost":3.89,"flags":1},
  {"from":47,"to":127,"cost":12.48,"flags":1},
  {"from":72,"to":43,"cost":7.95,"flags":1},
  {"from":72,"to":36,"cost":5.1,"flags":1},
  {"from":72,"to":47,"cost":3.89,"flags":1},
  {"from":71,"to":99,"cost":2.85,"flags":1},
  {"from":71,"to":89,"cost":6.36,"flags":1},
  {"from":71,"to":69,"cost":8.2,"flags":1},
  {"from":71,"to":138,"cost":5.19,"flags":1},
  {"from":102,"to":99,"cost":4.16,"flags":1},
  {"from":102,"to":67,"cost":8.23,"flags":1},
  {"from":102,"to":69,"cost":7.45,"flags":1},
  {"from":69,"to":99,"cost":9.03,"flags":1},
  {"from":69,"to":67,"cost":4.01,"flags":1},
  {"from":69,"to":71,"cost":8.2,"flags":1},
  {"from":69,"to":102,"cost":7.45,"flags":1},
  {"from":62,"to":49,"cost":4.48,"flags":1},
  {"from":62,"to":82,"cost":4.79,"flags":1},
  {"from":62,"to":132,"cost":9.44,"flags":1},
  {"from":82,"to":52,"cost":4.32,"flags":1},
  {"from":82,"to":62,"cost":4.79,"flags":1},
  {"from":82,"to":132,"cost":7,"flags":1},
  {"from":80,"to":52,"cost":9.45,"flags":1},
  {"from":80,"to":128,"cost":13.84,"flags":1},
  {"from":80,"to":96,"cost":8.44,"flags":1},
  {"from":96,"to":52,"cost":6.3,"flags":1},
  {"from":96,"to":80,"cost":8.44,"flags":1},
  {"from":63,"to":42,"cost":4.9,"flags":1},
  {"from":63,"to":75,"cost":4.11,"flags":1},
  {"from":63,"to":111,"cost":6.79,"flags":1},
  {"from":63,"to":110,"cost":9.54,"flags":1},
  {"from":111,"to":42,"cost":7.32,"flags":1},
  {"from":111,"to":77,"cost":9.4,"flags":1},
  {"from":111,"to":63,"cost":6.79,"flags":1},
  {"from":111,"to":110,"cost":7,"flags":1},
  {"from":110,"to":77,"cost":5.69,"flags":1},
  {"from":110,"to":63,"cost":9.54,"flags":1},
  {"from":110,"to":111,"cost":7,"flags":1},
  {"from":39,"to":14,"cost":2.09,"flags":1},
  {"from":39,"to":113,"cost":12.06,"flags":1},
  {"from":39,"to":65,"cost":6.19,"flags":1},
  {"from":136,"to":16,"cost":4.88,"flags":1},
  {"from":38,"to":60,"cost":4.05,"flags":1},
  {"from":38,"to":13,"cost":16.06,"flags":1},
  {"from":78,"to":44,"cost":5,"flags":1},
  {"from":78,"to":41,"cost":4.51,"flags":1},
  {"from":61,"to":37,"cost":1.46,"flags":1},
  {"from":64,"to":58,"cost":2.35,"flags":32},
  {"from":64,"to":21,"cost":10.97,"flags":1},
  {"from":64,"to":9,"cost":3.68,"flags":1},
  {"from":58,"to":64,"cost":2.35,"flags":32},
  {"from":58,"to":142,"cost":5.22,"flags":1},
  {"from":58,"to":121,"cost":2.22,"flags":1},
  {"from":58,"to":126,"cost":4.32,"flags":9},
  {"from":58,"to":147,"cost":4.42,"flags":9},
  {"from":154,"to":87,"cost":2.35,"flags":32},
  {"from":154,"to":163,"cost":3.79,"flags":1},
  {"from":87,"to":154,"cost":2.35,"flags":32},
  {"from":87,"to":33,"cost":3.55,"flags":1},
  {"from":114,"to":85,"cost":2.35,"flags":32},
  {"from":114,"to":148,"cost":4.15,"flags":1},
  {"from":114,"to":149,"cost":2.08,"flags":1},
  {"from":114,"to":150,"cost":2.04,"flags":1},
  {"from":85,"to":114,"cost":2.35,"flags":32},
  {"from":85,"to":18,"cost":3.8,"flags":1},
  {"from":66,"to":83,"cost":2.35,"flags":32},
  {"from":66,"to":15,"cost":10.92,"flags":1},
  {"from":66,"to":2,"cost":3.73,"flags":1},
  {"from":83,"to":66,"cost":2.35,"flags":32},
  {"from":83,"to":157,"cost":6.9,"flags":1},
  {"from":83,"to":122,"cost":1.75,"flags":1},
  {"from":83,"to":101,"cost":2.71,"flags":1},
  {"from":158,"to":142,"cost":1.1,"flags":1},
  {"from":157,"to":83,"cost":6.9,"flags":1},
  {"from":157,"to":101,"cost":4.24,"flags":1},
  {"from":160,"to":93,"cost":2.35,"flags":32},
  {"from":160,"to":35,"cost":5.8,"flags":1},
  {"from":93,"to":160,"cost":2.35,"flags":32},
  {"from":93,"to":16,"cost":8.16,"flags":1},
  {"from":156,"to":68,"cost":2.35,"flags":32},
  {"from":156,"to":29,"cost":6.9,"flags":1},
  {"from":68,"to":156,"cost":2.35,"flags":32},
  {"from":68,"to":37,"cost":7.75,"flags":9},
  {"from":68,"to":41,"cost":7.79,"flags":1},
  {"from":35,"to":20,"cost":6.89,"flags":1},
  {"from":35,"to":160,"cost":5.8,"flags":1},
  {"from":35,"to":84,"cost":12.32,"flags":1},
  {"from":35,"to":27,"cost":7.91,"flags":1},
  {"from":35,"to":40,"cost":8.31,"flags":1},
  {"from":35,"to":53,"cost":8.94,"flags":1},
  {"from":29,"to":25,"cost":7.72,"flags":1},
  {"from":29,"to":31,"cost":11.64,"flags":1},
  {"from":29,"to":156,"cost":6.9,"flags":1},
  {"from":29,"to":8,"cost":7.66,"flags":1},
  {"from":29,"to":32,"cost":8.75,"flags":1},
  {"from":29,"to":17,"cost":8.34,"flags":1},
  {"from":51,"to":94,"cost":8.6,"flags":1},
  {"from":51,"to":50,"cost":0.94,"flags":1},
  {"from":98,"to":93,"cost":3.09,"flags":9},
  {"from":98,"to":113,"cost":5.28,"flags":1},
  {"from":98,"to":65,"cost":6.42,"flags":1},
  {"from":98,"to":79,"cost":4.15,"flags":1},
  {"from":84,"to":48,"cost":3.94,"flags":1},
  {"from":84,"to":35,"cost":12.32,"flags":1},
  {"from":84,"to":10,"cost":8.36,"flags":1},
  {"from":22,"to":13,"cost":13.27,"flags":1},
  {"from":22,"to":48,"cost":2.92,"flags":1},
  {"from":22,"to":27,"cost":13.89,"flags":1},
  {"from":22,"to":40,"cost":15.52,"flags":1},
  {"from":22,"to":53,"cost":12.04,"flags":1},
  {"from":22,"to":23,"cost":5.41,"flags":1},
  {"from":22,"to":10,"cost":3.74,"flags":1},
  {"from":5,"to":13,"cost":6.36,"flags":1},
  {"from":5,"to":15,"cost":4.68,"flags":1},
  {"from":5,"to":2,"cost":10.02,"flags":1},
  {"from":5,"to":18,"cost":8.86,"flags":1},
  {"from":5,"to":19,"cost":3.05,"flags":1},
  {"from":5,"to":23,"cost":13.33,"flags":1},
  {"from":37,"to":61,"cost":1.46,"flags":1},
  {"from":37,"to":68,"cost":7.75,"flags":9},
  {"from":37,"to":94,"cost":8.05,"flags":1},
  {"from":37,"to":74,"cost":9.41,"flags":1},
  {"from":37,"to":41,"cost":2.8,"flags":1},
  {"from":127,"to":143,"cost":11.86,"flags":1},
  {"from":127,"to":47,"cost":12.48,"flags":1},
  {"from":97,"to":105,"cost":0.73,"flags":1},
  {"from":97,"to":112,"cost":6.96,"flags":1},
  {"from":1,"to":60,"cost":7.93,"flags":9},
  {"from":1,"to":92,"cost":8.59,"flags":9},
  {"from":1,"to":59,"cost":15.23,"flags":9},
  {"from":1,"to":56,"cost":7.88,"flags":9},
  {"from":152,"to":97,"cost":11.75,"flags":32},
  {"from":97,"to":152,"cost":11.75,"flags":32},
  {"from":152,"to":1,"cost":11.75,"flags":32},
  {"from":1,"to":152,"cost":11.75,"flags":32},
  {"from":14,"to":39,"cost":2.09,"flags":1},
  {"from":14,"to":16,"cost":1.65,"flags":1},
  {"from":14,"to":113,"cost":10.76,"flags":1},
  {"from":0,"to":57,"cost":9.15,"flags":9},
  {"from":0,"to":118,"cost":9.48,"flags":9},
  {"from":151,"to":14,"cost":11.75,"flags":32},
  {"from":14,"to":151,"cost":11.75,"flags":32},
  {"from":151,"to":0,"cost":11.75,"flags":32},
  {"from":0,"to":151,"cost":11.75,"flags":32},
  {"from":159,"to":86,"cost":11.75,"flags":32},
  {"from":86,"to":159,"cost":11.75,"flags":32},
  {"from":159,"to":4,"cost":11.75,"flags":32},
  {"from":4,"to":159,"cost":11.75,"flags":32},
  {"from":86,"to":103,"cost":1.42,"flags":1},
  {"from":86,"to":30,"cost":18.25,"flags":9},
  {"from":86,"to":133,"cost":8.27,"flags":1},
  {"from":86,"to":137,"cost":8.23,"flags":1},
  {"from":4,"to":81,"cost":7.28,"flags":9},
  {"from":4,"to":76,"cost":15.14,"flags":9},
  {"from":4,"to":119,"cost":11.88,"flags":9},
  {"from":4,"to":30,"cost":13.26,"flags":9},
  {"from":4,"to":73,"cost":14.73,"flags":9},
  {"from":8,"to":25,"cost":15.21,"flags":9},
  {"from":8,"to":26,"cost":11.8,"flags":1},
  {"from":8,"to":31,"cost":7.82,"flags":1},
  {"from":8,"to":29,"cost":7.66,"flags":1},
  {"from":8,"to":32,"cost":1.99,"flags":1},
  {"from":8,"to":17,"cost":2.29,"flags":1},
  {"from":8,"to":9,"cost":22.39,"flags":1},
  {"from":6,"to":3,"cost":15.78,"flags":1},
  {"from":6,"to":25,"cost":8.02,"flags":1},
  {"from":6,"to":21,"cost":6.15,"flags":1},
  {"from":6,"to":17,"cost":23.38,"flags":1},
  {"from":6,"to":9,"cost":1.64,"flags":1},
  {"from":6,"to":33,"cost":1.73,"flags":1},
  {"from":6,"to":28,"cost":7.64,"flags":1},
  {"from":21,"to":25,"cost":9.47,"flags":1},
  {"from":21,"to":64,"cost":10.97,"flags":1},
  {"from":21,"to":6,"cost":6.15,"flags":1},
  {"from":21,"to":9,"cost":7.45,"flags":1},
  {"from":21,"to":33,"cost":4.91,"flags":1},
  {"from":21,"to":28,"cost":2.03,"flags":1},
  {"from":32,"to":25,"cost":16.44,"flags":1},
  {"from":32,"to":26,"cost":10.11,"flags":1},
  {"from":32,"to":34,"cost":7.08,"flags":1},
  {"from":32,"to":31,"cost":5.99,"flags":1},
  {"from":32,"to":29,"cost":8.75,"flags":1},
  {"from":32,"to":8,"cost":1.99,"flags":1},
  {"from":32,"to":12,"cost":12.97,"flags":1},
  {"from":17,"to":29,"cost":8.34,"flags":1},
  {"from":17,"to":8,"cost":2.29,"flags":1},
  {"from":17,"to":6,"cost":23.38,"flags":1},
  {"from":9,"to":25,"cost":7.2,"flags":1},
  {"from":9,"to":64,"cost":3.68,"flags":1},
  {"from":9,"to":8,"cost":22.39,"flags":1},
  {"from":9,"to":6,"cost":1.64,"flags":1},
  {"from":9,"to":21,"cost":7.45,"flags":1},
  {"from":33,"to":87,"cost":3.55,"flags":1},
  {"from":33,"to":6,"cost":1.73,"flags":1},
  {"from":33,"to":21,"cost":4.91,"flags":1},
  {"from":33,"to":28,"cost":6.65,"flags":1},
  {"from":28,"to":3,"cost":8.56,"flags":1},
  {"from":28,"to":6,"cost":7.64,"flags":1},
  {"from":28,"to":21,"cost":2.03,"flags":1},
  {"from":28,"to":33,"cost":6.65,"flags":1},
  {"from":28,"to":24,"cost":15.96,"flags":1},
  {"from":24,"to":3,"cost":7.78,"flags":1},
  {"from":24,"to":26,"cost":5.37,"flags":1},
  {"from":24,"to":34,"cost":5.91,"flags":1},
  {"from":24,"to":28,"cost":15.96,"flags":1},
  {"from":24,"to":12,"cost":2.15,"flags":1},
  {"from":12,"to":26,"cost":3.95,"flags":1},
  {"from":12,"to":34,"cost":5.92,"flags":1},
  {"from":12,"to":32,"cost":12.97,"flags":1},
  {"from":12,"to":24,"cost":2.15,"flags":1},
  {"from":133,"to":103,"cost":8.06,"flags":1},
  {"from":133,"to":86,"cost":8.27,"flags":1},
  {"from":133,"to":129,"cost":2.01,"flags":1},
  {"from":137,"to":103,"cost":7.43,"flags":1},
  {"from":137,"to":86,"cost":8.23,"flags":1},
  {"from":137,"to":129,"cost":1.65,"flags":1},
  {"from":142,"to":58,"cost":5.22,"flags":1},
  {"from":142,"to":158,"cost":1.1,"flags":1},
  {"from":142,"to":121,"cost":3.61,"flags":1},
  {"from":121,"to":58,"cost":2.22,"flags":1},
  {"from":121,"to":142,"cost":3.61,"flags":1},
  {"from":121,"to":126,"cost":4.66,"flags":1},
  {"from":121,"to":147,"cost":2.55,"flags":1},
  {"from":88,"to":91,"cost":7.33,"flags":1},
  {"from":88,"to":108,"cost":7.83,"flags":1},
  {"from":88,"to":109,"cost":2.07,"flags":1},
  {"from":88,"to":141,"cost":17.64,"flags":1},
  {"from":44,"to":78,"cost":5,"flags":1},
  {"from":44,"to":68,"cost":5.43,"flags":9},
  {"from":44,"to":50,"cost":3.98,"flags":1},
  {"from":44,"to":41,"cost":5.74,"flags":1},
  {"from":94,"to":78,"cost":12.59,"flags":9},
  {"from":94,"to":51,"cost":8.6,"flags":1},
  {"from":94,"to":37,"cost":8.05,"flags":1},
  {"from":94,"to":74,"cost":1.43,"flags":1},
  {"from":94,"to":41,"cost":9.47,"flags":1},
  {"from":74,"to":37,"cost":9.41,"flags":1},
  {"from":74,"to":94,"cost":1.43,"flags":1},
  {"from":74,"to":50,"cost":7.75,"flags":1},
  {"from":74,"to":41,"cost":10.69,"flags":1},
  {"from":50,"to":68,"cost":4.43,"flags":9},
  {"from":50,"to":51,"cost":0.94,"flags":1},
  {"from":50,"to":44,"cost":3.98,"flags":1},
  {"from":50,"to":74,"cost":7.75,"flags":1},
  {"from":41,"to":78,"cost":4.51,"flags":1},
  {"from":41,"to":68,"cost":7.79,"flags":1},
  {"from":41,"to":51,"cost":9.78,"flags":1},
  {"from":41,"to":37,"cost":2.8,"flags":1},
  {"from":41,"to":44,"cost":5.74,"flags":1},
  {"from":41,"to":94,"cost":9.47,"flags":1},
  {"from":16,"to":136,"cost":4.88,"flags":1},
  {"from":16,"to":93,"cost":8.16,"flags":1},
  {"from":16,"to":14,"cost":1.65,"flags":1},
  {"from":16,"to":106,"cost":8.33,"flags":1},
  {"from":16,"to":113,"cost":9.13,"flags":1},
  {"from":16,"to":65,"cost":6.24,"flags":1},
  {"from":122,"to":83,"cost":1.75,"flags":1},
  {"from":122,"to":101,"cost":2.18,"flags":1},
  {"from":122,"to":100,"cost":3.01,"flags":9},
  {"from":122,"to":125,"cost":5.44,"flags":9},
  {"from":15,"to":20,"cost":11.58,"flags":1},
  {"from":15,"to":66,"cost":10.92,"flags":1},
  {"from":15,"to":5,"cost":4.68,"flags":1},
  {"from":15,"to":2,"cost":7.38,"flags":1},
  {"from":15,"to":18,"cost":5.12,"flags":1},
  {"from":15,"to":11,"cost":6.15,"flags":1},
  {"from":15,"to":19,"cost":1.7,"flags":1},
  {"from":101,"to":83,"cost":2.71,"flags":1},
  {"from":101,"to":157,"cost":4.24,"flags":1},
  {"from":101,"to":122,"cost":2.18,"flags":1},
  {"from":101,"to":100,"cost":3.49,"flags":1},
  {"from":101,"to":125,"cost":3.83,"flags":1},
  {"from":106,"to":16,"cost":8.33,"flags":1},
  {"from":106,"to":113,"cost":1.18,"flags":1},
  {"from":113,"to":39,"cost":12.06,"flags":1},
  {"from":113,"to":98,"cost":5.28,"flags":1},
  {"from":113,"to":14,"cost":10.76,"flags":1},
  {"from":113,"to":16,"cost":9.13,"flags":1},
  {"from":113,"to":106,"cost":1.18,"flags":1},
  {"from":65,"to":39,"cost":6.19,"flags":1},
  {"from":65,"to":93,"cost":5.34,"flags":9},
  {"from":65,"to":16,"cost":6.24,"flags":1},
  {"from":65,"to":79,"cost":3.77,"flags":1},
  {"from":79,"to":93,"cost":4.44,"flags":9},
  {"from":79,"to":98,"cost":4.15,"flags":1},
  {"from":79,"to":65,"cost":3.77,"flags":1},
  {"from":27,"to":48,"cost":12.41,"flags":1},
  {"from":27,"to":35,"cost":7.91,"flags":1},
  {"from":27,"to":22,"cost":13.89,"flags":1},
  {"from":27,"to":40,"cost":1.64,"flags":1},
  {"from":27,"to":53,"cost":2.18,"flags":1},
  {"from":27,"to":2,"cost":22.28,"flags":1},
  {"from":131,"to":135,"cost":3.14,"flags":1},
  {"from":131,"to":112,"cost":1.8,"flags":1},
  {"from":135,"to":131,"cost":3.14,"flags":1},
  {"from":135,"to":112,"cost":2,"flags":1},
  {"from":40,"to":48,"cost":14.02,"flags":1},
  {"from":40,"to":35,"cost":8.31,"flags":1},
  {"from":40,"to":27,"cost":1.64,"flags":1},
  {"from":40,"to":11,"cost":22.89,"flags":1},
  {"from":53,"to":48,"cost":10.37,"flags":1},
  {"from":53,"to":35,"cost":8.94,"flags":1},
  {"from":53,"to":22,"cost":12.04,"flags":1},
  {"from":53,"to":27,"cost":2.18,"flags":1},
  {"from":53,"to":10,"cost":13.19,"flags":1},
  {"from":2,"to":20,"cost":8.9,"flags":1},
  {"from":2,"to":66,"cost":3.73,"flags":1},
  {"from":2,"to":5,"cost":10.02,"flags":9},
  {"from":2,"to":15,"cost":7.38,"flags":1},
  {"from":2,"to":27,"cost":22.28,"flags":1},
  {"from":2,"to":11,"cost":1.53,"flags":1},
  {"from":2,"to":19,"cost":8.43,"flags":1},
  {"from":18,"to":13,"cost":15.11,"flags":1},
  {"from":18,"to":20,"cost":10.87,"flags":1},
  {"from":18,"to":85,"cost":3.8,"flags":1},
  {"from":18,"to":5,"cost":8.86,"flags":9},
  {"from":18,"to":15,"cost":5.12,"flags":1},
  {"from":18,"to":11,"cost":1.51,"flags":1},
  {"from":18,"to":19,"cost":6.54,"flags":1},
  {"from":11,"to":13,"cost":15.65,"flags":9},
  {"from":11,"to":20,"cost":9.81,"flags":1},
  {"from":11,"to":15,"cost":6.15,"flags":1},
  {"from":11,"to":40,"cost":22.89,"flags":1},
  {"from":11,"to":2,"cost":1.53,"flags":1},
  {"from":11,"to":18,"cost":1.51,"flags":1},
  {"from":11,"to":19,"cost":7.37,"flags":1},
  {"from":19,"to":5,"cost":3.05,"flags":1},
  {"from":19,"to":15,"cost":1.7,"flags":1},
  {"from":19,"to":2,"cost":8.43,"flags":1},
  {"from":19,"to":18,"cost":6.54,"flags":1},
  {"from":19,"to":11,"cost":7.37,"flags":1},
  {"from":19,"to":23,"cost":16.16,"flags":1},
  {"from":23,"to":13,"cost":7.89,"flags":1},
  {"from":23,"to":48,"cost":7.77,"flags":1},
  {"from":23,"to":22,"cost":5.41,"flags":1},
  {"from":23,"to":5,"cost":13.33,"flags":1},
  {"from":23,"to":19,"cost":16.16,"flags":1},
  {"from":23,"to":10,"cost":1.85,"flags":1},
  {"from":10,"to":48,"cost":6.36,"flags":1},
  {"from":10,"to":84,"cost":8.36,"flags":1},
  {"from":10,"to":22,"cost":3.74,"flags":1},
  {"from":10,"to":53,"cost":13.19,"flags":1},
  {"from":10,"to":23,"cost":1.85,"flags":1},
  {"from":129,"to":103,"cost":7.94,"flags":1},
  {"from":129,"to":133,"cost":2.01,"flags":1},
  {"from":129,"to":137,"cost":1.65,"flags":1},
  {"from":112,"to":97,"cost":6.96,"flags":1},
  {"from":112,"to":131,"cost":1.8,"flags":1},
  {"from":112,"to":135,"cost":2,"flags":1},
  {"from":148,"to":114,"cost":4.15,"flags":1},
  {"from":148,"to":149,"cost":4.55,"flags":1},
  {"from":148,"to":150,"cost":4.53,"flags":1},
  {"from":163,"to":154,"cost":3.79,"flags":1},
  {"from":130,"to":42,"cost":6.42,"flags":9},
  {"from":130,"to":75,"cost":8.95,"flags":1},
  {"from":130,"to":123,"cost":7.26,"flags":1},
  {"from":132,"to":52,"cost":8.76,"flags":1},
  {"from":132,"to":49,"cost":9.94,"flags":1},
  {"from":132,"to":62,"cost":9.44,"flags":1},
  {"from":132,"to":82,"cost":7,"flags":1},
  {"from":138,"to":89,"cost":8.02,"flags":1},
  {"from":138,"to":71,"cost":5.19,"flags":1},
  {"from":134,"to":43,"cost":7.29,"flags":1},
  {"from":134,"to":54,"cost":7.68,"flags":1},
  {"from":134,"to":36,"cost":11.41,"flags":1},
  {"from":100,"to":122,"cost":3.01,"flags":9},
  {"from":100,"to":101,"cost":3.49,"flags":1},
  {"from":100,"to":162,"cost":3.23,"flags":1},
  {"from":125,"to":122,"cost":5.44,"flags":1},
  {"from":125,"to":101,"cost":3.83,"flags":1},
  {"from":125,"to":164,"cost":3.69,"flags":1},
  {"from":164,"to":125,"cost":3.69,"flags":1},
  {"from":162,"to":100,"cost":3.23,"flags":1},
  {"from":149,"to":114,"cost":2.08,"flags":1},
  {"from":149,"to":148,"cost":4.55,"flags":1},
  {"from":150,"to":114,"cost":2.04,"flags":1},
  {"from":150,"to":148,"cost":4.53,"flags":1},
  {"from":126,"to":58,"cost":4.32,"flags":1},
  {"from":126,"to":121,"cost":4.66,"flags":1},
  {"from":126,"to":165,"cost":3.74,"flags":1},
  {"from":126,"to":147,"cost":7.01,"flags":1},
  {"from":165,"to":126,"cost":3.74,"flags":1},
  {"from":147,"to":121,"cost":2.55,"flags":9},
  {"from":147,"to":126,"cost":7.01,"flags":1},
];

// Out-edges per node, built once at require time rather than stored twice in the file.
const ADJACENCY = NODES.map(() => []);
for (const e of EDGES) ADJACENCY[e.from].push(e);

const dist3 = (a, b) => Math.hypot(a.x - b.x, a.y - b.y, a.z - b.z);

/**
 * The nav node closest to a point, by plain 3D distance.
 *
 * 3D and not 2D on purpose: CTF-Face stacks nodes vertically inside both towers, so a
 * ground-plane nearest would happily hand a bot on the floor a waypoint three storeys
 * up. 166 nodes is small enough that the linear scan is not worth indexing.
 *
 * @param {number} x @param {number} y @param {number} z  scene units
 * @param {object} [opts]
 * @param {number} [opts.maxDist=Infinity]  give up beyond this and return null
 * @param {boolean} [opts.walkableOnly=true]  only consider the main walkable component
 * @param {(node) => boolean} [opts.filter]  extra predicate, e.g. n => n.cls === "DefensePoint"
 * @returns {object|null} the node, or null if nothing qualified
 */
function nearestNode(x, y, z, opts = {}) {
  const { maxDist = Infinity, walkableOnly = true, filter } = opts;
  const p = { x, y, z };
  let best = null;
  let bestD = maxDist;
  for (const n of NODES) {
    if (walkableOnly && !WALKABLE_MAIN.has(n.id)) continue;
    if (filter && !filter(n)) continue;
    const d = dist3(n, p);
    if (d < bestD) {
      bestD = d;
      best = n;
    }
  }
  return best;
}

/**
 * Shortest route through the graph, A* with a straight-line heuristic.
 *
 * @param {number} fromId @param {number} toId  node ids (indices into NODES)
 * @param {object} [opts]
 * @param {boolean} [opts.special=false]  allow R_SPECIAL edges (teleporters and
 *        translocator pads). Off by default: this game implements neither, so a route
 *        through one is a route the bot cannot actually take. Turning it on also turns
 *        the heuristic off — an R_SPECIAL edge carries a flat nominal cost far below the
 *        distance it covers, which would make a straight-line estimate inadmissible — so
 *        the search degrades to Dijkstra. Still optimal, just less directed.
 * @returns {number[]|null} node ids from fromId to toId inclusive, or null if unreachable
 */
function aStar(fromId, toId, opts = {}) {
  const allowSpecial = opts.special === true;
  if (!NODES[fromId] || !NODES[toId]) return null;
  if (fromId === toId) return [fromId];

  const goal = NODES[toId];
  const h = allowSpecial ? () => 0 : (n) => dist3(n, goal);
  const g = new Float64Array(NODES.length).fill(Infinity);
  const cameFrom = new Int32Array(NODES.length).fill(-1);
  const closed = new Uint8Array(NODES.length);
  g[fromId] = 0;

  // Binary min-heap of [f, nodeId]. Stale entries are skipped via `closed`.
  const heap = [[h(NODES[fromId]), fromId]];
  const push = (item) => {
    heap.push(item);
    let i = heap.length - 1;
    while (i > 0) {
      const p = (i - 1) >> 1;
      if (heap[p][0] <= heap[i][0]) break;
      [heap[p], heap[i]] = [heap[i], heap[p]];
      i = p;
    }
  };
  const pop = () => {
    const top = heap[0];
    const last = heap.pop();
    if (heap.length) {
      heap[0] = last;
      let i = 0;
      for (;;) {
        const l = 2 * i + 1;
        const r = l + 1;
        let s = i;
        if (l < heap.length && heap[l][0] < heap[s][0]) s = l;
        if (r < heap.length && heap[r][0] < heap[s][0]) s = r;
        if (s === i) break;
        [heap[s], heap[i]] = [heap[i], heap[s]];
        i = s;
      }
    }
    return top;
  };

  while (heap.length) {
    const [, current] = pop();
    if (closed[current]) continue;
    if (current === toId) {
      const out = [current];
      for (let v = cameFrom[current]; v >= 0; v = cameFrom[v]) out.push(v);
      return out.reverse();
    }
    closed[current] = 1;
    for (const e of ADJACENCY[current]) {
      if (!allowSpecial && e.flags & REACH_FLAGS.SPECIAL) continue;
      if (closed[e.to]) continue;
      const tentative = g[current] + e.cost;
      if (tentative >= g[e.to]) continue;
      g[e.to] = tentative;
      cameFrom[e.to] = current;
      push([tentative + h(NODES[e.to]), e.to]);
    }
  }
  return null;
}

// The node ids reachable from each other without an R_SPECIAL edge — the part of the
// map a bot in this game can actually walk. Computed here rather than baked in as a
// list so it can never disagree with EDGES.
const WALKABLE_MAIN = (() => {
  const undirected = NODES.map(() => []);
  for (const e of EDGES) {
    if (e.flags & REACH_FLAGS.SPECIAL) continue;
    undirected[e.from].push(e.to);
    undirected[e.to].push(e.from);
  }
  const seen = new Int32Array(NODES.length).fill(-1);
  let best = [];
  for (let i = 0; i < NODES.length; i++) {
    if (seen[i] >= 0) continue;
    const group = [];
    const stack = [i];
    seen[i] = i;
    while (stack.length) {
      const v = stack.pop();
      group.push(v);
      for (const w of undirected[v]) {
        if (seen[w] < 0) {
          seen[w] = i;
          stack.push(w);
        }
      }
    }
    if (group.length > best.length) best = group;
  }
  return new Set(best);
})();

module.exports = { NODES, EDGES, ADJACENCY, REACH_FLAGS, WALKABLE_MAIN, nearestNode, aStar };
