// GENERATED by scripts/gen-weapons.mjs — DO NOT EDIT.
//
// CTF-Face's weapons, as far as they are implemented. Damage and cadence are UT99's
// own numbers; the held model is the pickup mesh, the way the Enforcer already works.
//
// NOT HERE YET: the Rocket Launcher, Ripper and Redeemer. All three are projectile
// weapons — travel time, splash, bouncing blades — and the game resolves every shot as
// an instant hit. Their pickups stand on the map and respawn, and picking one up does
// nothing, which is honest: arming someone with a rocket launcher that fires hitscan
// pistol rounds would be a worse lie than leaving it inert.

const WEAPONS = {
  "enforcer": {
    "name": "Enforcer",
    "damage": 17,
    "fireRate": 4
  },
  "sniper": {
    "name": "Sniper Rifle",
    "damage": 45,
    "fireRate": 0.6666666666666666
  },
  "shock": {
    "name": "Shock Rifle",
    "damage": 40,
    "fireRate": 1.6666666666666667
  }
};

const DEFAULT_WEAPON = "enforcer";
const WEAPON_BY_PICKUP = {
  "weapon-sniper": "sniper",
  "weapon-shock": "shock"
};

/** The weapon for an id, falling back to the one everyone spawns with. */
function weapon(id) {
  return WEAPONS[id] || WEAPONS[DEFAULT_WEAPON];
}

module.exports = { WEAPONS, DEFAULT_WEAPON, WEAPON_BY_PICKUP, weapon };
