// GENERATED by scripts/gen-weapons.mjs — DO NOT EDIT.
//
// CTF-Face's weapons, as far as they are implemented. Damage and cadence are UT99's
// own numbers; the held model is the pickup mesh, the way the Enforcer already works.
//
// Six weapons: three hitscan, three that fly. A projectile weapon carries a "projectile"
// block the server uses to simulate it — speed in metres per second, splash radius in
// metres, and a wall-hit budget. Those are UT99's own figures converted once; the
// fireRate beside them is not: UT99 has no shot interval to read, so cadence is chosen.

const WEAPONS = {
  "enforcer": {
    "name": "Enforcer",
    "damage": 17,
    "fireRate": 4
  },
  "sniper": {
    "name": "Sniper Rifle",
    "damage": 45,
    "fireRate": 0.6666666666666666,
    "headshotDamage": 100
  },
  "shock": {
    "name": "Shock Rifle",
    "damage": 40,
    "fireRate": 1.6666666666666667
  },
  "rocket": {
    "name": "Rocket Launcher",
    "damage": 75,
    "fireRate": 0.9090909090909091,
    "projectile": {
      "type": "rocket",
      "speed": 21.15,
      "splashRadius": 5.17,
      "lifeMs": 6000,
      "bounces": 0,
      "model": "assets/3d/projectiles/rocket/rocket.gltf"
    }
  },
  "ripper": {
    "name": "Ripper",
    "damage": 30,
    "fireRate": 1.6666666666666667,
    "headshotDamage": 105,
    "projectile": {
      "type": "ripper",
      "speed": 30.55,
      "splashRadius": 0,
      "lifeMs": 6000,
      "bounces": 6,
      "model": "assets/3d/projectiles/ripper/ripper.gltf"
    }
  },
  "redeemer": {
    "name": "Redeemer",
    "damage": 1000,
    "fireRate": 0.4,
    "projectile": {
      "type": "redeemer",
      "speed": 14.1,
      "splashRadius": 7.05,
      "lifeMs": 6000,
      "bounces": 0,
      "model": "assets/3d/projectiles/redeemer/redeemer.gltf"
    }
  }
};

const DEFAULT_WEAPON = "enforcer";
const WEAPON_BY_PICKUP = {
  "weapon-sniper": "sniper",
  "weapon-shock": "shock",
  "weapon-rocket": "rocket",
  "weapon-ripper": "ripper",
  "weapon-redeemer": "redeemer"
};
const PAWN = {"radius":0.4,"height":1.833,"headshotAboveCentre":0.568};
const PICKUP_SOUND = "assets/audio/ut/weaponpickup.mp3";

/** The weapon for an id, falling back to the one everyone spawns with. */
function weapon(id) {
  return WEAPONS[id] || WEAPONS[DEFAULT_WEAPON];
}

module.exports = { WEAPONS, DEFAULT_WEAPON, WEAPON_BY_PICKUP, PAWN, PICKUP_SOUND, weapon };
