// GENERATED by scripts/gen-characters.mjs — DO NOT EDIT.
//
// Every playable UT99 character extracted into assets/3d/characters, as one flat list
// the server can index into and the client can turn into URLs.
//
// 8 models, 23 variants. Each model is one glTF with Idle/Walk/Run as
// morph-target animations (UT99 characters are vertex-animated, not skinned) and one
// material slot per skin texture. The slot count differs per model, so SKINS carries
// the file list rather than a count.
//
// The server assigns a variant per player and broadcasts the index, so every client
// draws the same body for the same person. See server/characters.js.

const BASE = "assets/3d/characters";

const MODELS = {
  "boss": {
    "gltf": "boss.gltf",
    "yawDeg": 0,
    "skins": {
      "xan": [
        "s0.png",
        "s1.png",
        "s2.png",
        "s3.png",
        "s4.png"
      ]
    }
  },
  "commando": {
    "gltf": "commando.gltf",
    "yawDeg": 0,
    "skins": {
      "gorn": [
        "s0.png",
        "s1.png",
        "s2.png",
        "s3.png"
      ],
      "graves": [
        "s0.png",
        "s1.png",
        "s2.png",
        "s3.png"
      ],
      "kragoth": [
        "s0.png",
        "s1.png",
        "s2.png",
        "s3.png"
      ],
      "malakai": [
        "s0.png",
        "s1.png",
        "s2.png",
        "s3.png"
      ]
    }
  },
  "fcommando": {
    "gltf": "fcommando.gltf",
    "yawDeg": 0,
    "skins": {
      "gromida": [
        "s0.png",
        "s1.png",
        "s2.png"
      ],
      "ivana": [
        "s0.png",
        "s1.png",
        "s2.png"
      ],
      "jayce": [
        "s0.png",
        "s1.png",
        "s2.png"
      ],
      "nikita": [
        "s0.png",
        "s1.png",
        "s2.png"
      ]
    }
  },
  "nali": {
    "gltf": "nali.gltf",
    "yawDeg": 0,
    "skins": {
      "default": [
        "s0.png",
        "s1.png"
      ]
    }
  },
  "sgirl": {
    "gltf": "sgirl.gltf",
    "yawDeg": 0,
    "skins": {
      "aryss": [
        "s0.png",
        "s1.png",
        "s2.png",
        "s3.png"
      ],
      "athena": [
        "s0.png",
        "s1.png",
        "s2.png",
        "s3.png"
      ],
      "ryanna": [
        "s0.png",
        "s1.png",
        "s2.png",
        "s3.png"
      ],
      "tasha": [
        "s0.png",
        "s1.png",
        "s2.png",
        "s3.png"
      ]
    }
  },
  "skaarj": {
    "gltf": "skaarj.gltf",
    "yawDeg": 0,
    "skins": {
      "baetal": [
        "s0.png",
        "s1.png",
        "s2.png"
      ],
      "disconnect": [
        "s0.png",
        "s1.png",
        "s2.png"
      ],
      "pharoh": [
        "s0.png",
        "s1.png",
        "s2.png"
      ],
      "skrilax": [
        "s0.png",
        "s1.png",
        "s2.png"
      ]
    }
  },
  "soldier": {
    "gltf": "soldier.gltf",
    "yawDeg": 0,
    "skins": {
      "malcom": [
        "s0.png",
        "s1.png",
        "s2.png",
        "s3.png"
      ],
      "manwell": [
        "s0.png",
        "s1.png",
        "s2.png",
        "s3.png"
      ],
      "radkin": [
        "s0.png",
        "s1.png",
        "s2.png",
        "s3.png"
      ],
      "rankin": [
        "s0.png",
        "s1.png",
        "s2.png",
        "s3.png"
      ]
    }
  },
  "warcow": {
    "gltf": "warcow.gltf",
    "yawDeg": 0,
    "skins": {
      "default": [
        "s0.png",
        "s1.png",
        "s2.png"
      ]
    }
  }
};

const VARIANTS = [["boss","xan"],["commando","gorn"],["commando","graves"],["commando","kragoth"],["commando","malakai"],["fcommando","gromida"],["fcommando","ivana"],["fcommando","jayce"],["fcommando","nikita"],["nali","default"],["sgirl","aryss"],["sgirl","athena"],["sgirl","ryanna"],["sgirl","tasha"],["skaarj","baetal"],["skaarj","disconnect"],["skaarj","pharoh"],["skaarj","skrilax"],["soldier","malcom"],["soldier","manwell"],["soldier","radkin"],["soldier","rankin"],["warcow","default"]];

/**
 * Model URL for a variant index, or null when the index is unknown.
 *
 * `prefix` is for pages that are not at the site root: the game is served from /, the
 * AR spectator page from /ar/, and the paths here are relative so both can be hosted
 * under any path prefix. The AR page passes "../", as ar-config.js does for its own
 * assets.
 */
function modelUrl(index, prefix = "") {
  const v = VARIANTS[index];
  if (!v) return null;
  return `${prefix}${BASE}/${v[0]}/${MODELS[v[0]].gltf}`;
}

/** Skin texture URLs, one per material slot, for a variant index. */
function skinUrls(index, prefix = "") {
  const v = VARIANTS[index];
  if (!v) return [];
  return MODELS[v[0]].skins[v[1]].map((f) => `${prefix}${BASE}/${v[0]}/${v[1]}/${f}`);
}

const CHARACTER_COUNT = VARIANTS.length;

/**
 * Degrees to turn this model so it faces the way the game thinks it does.
 *
 * Zero for all eight, and that is the point: scripts/build-ut-characters.mjs bakes Epic's
 * RotOrigin in, so every body already faces -Z, the rig's forward. It used to be 90 for
 * the Skaarj and the cow, which was a fitted number standing in for a rotator the old
 * extractor never applied — see the note in scripts/gen-characters.mjs.
 *
 * Kept because a future mesh may genuinely need it. Apply it to the MODEL, never to the
 * rig: the rig's yaw is the player's heading and is overwritten from the wire on every
 * pose, so a correction written there is erased by the next packet.
 */
function modelYaw(index) {
  const v = VARIANTS[index];
  if (!v) return 0;
  return MODELS[v[0]].yawDeg || 0;
}

export { BASE, MODELS, VARIANTS, CHARACTER_COUNT, modelUrl, skinUrls, modelYaw };
