// GENERATED by scripts/gen-effects.mjs — DO NOT EDIT.
//
// What UT99 draws where a shot LANDS: the Shock Rifle's beam and its expanding ring, the
// flash and smoke and sparks and chips and decal of a bullet hitting a wall, and the shell
// case the gun throws out. Every number is Epic's, read out of BotPack.u and UnrealShare.u
// by scripts/build-ut-effects.mjs — see its header for the UnrealScript each one came from.
//
// LENGTHS ARE METRES and times are SECONDS; the raw Unreal Units are kept beside the few
// that a reader would go looking for in the script. Rotation rates are radians per second,
// converted once from UE1's 65536-to-the-turn integers.
//
// TWO THINGS NOT TO DO TWICE:
//
//   Do not scale a model by its `drawScale`. Each glTF already has UT99's DrawScale
//   multiplied into its vertices. The field is here because it is Epic's number and
//   because one instance overrides it — `shellCase.sniperDrawScale` is a multiplier on
//   the committed model.
//
//   Do not rotate a model into another frame. They are emitted in the SCENE's axes
//   (src/shared/map-transform.js's uuToScene), so FORWARD IS +X and UP IS +Y. UT99 spawns
//   every one of them with Rotator(HitNormal) or rotator(fireDirection), so pointing model
//   +X along that vector is the whole of the placement.
//
// `blend: "additive"` is not a taste call either. These actors are STY_Translucent, and a
// translucent UE1 surface has BRIGHTNESS FOR OPACITY — black is invisible. Alpha-blend
// them instead and every effect draws as a black card. The one exception is the decal,
// which UE1 projects modulated so it darkens the wall.

/** Which model axis is the effect's "forward" — see the header. */
const FORWARD_AXIS = "+x";

const EFFECTS = {
  "shockBeam": {
    "model": "assets/3d/effects/shockbeam/shockbeam.gltf",
    "sizeM": [
      1.7328,
      0.0409,
      0.0577
    ],
    "bboxM": {
      "min": [
        0.0022,
        -0.0205,
        -0.0288
      ],
      "max": [
        1.7349,
        0.0205,
        0.0288
      ]
    },
    "drawScale": 0.44,
    "blend": "additive",
    "lifeSpan": 0.27,
    "spacingM": 3.173,
    "spacingUU": 135,
    "segmentIntervalS": 0.05,
    "muzzleForwardBonusM": 0.47,
    "rollRateRadPerSec": 95.8738,
    "randomStartRoll": true,
    "glowMax": 0.8235,
    "particles": {
      "texture": "jenergy2",
      "sizeM": 0.6618,
      "count": 40,
      "pointsM": [
        [
          0.4126,
          -0.0149,
          -0.0102
        ],
        [
          0.6579,
          0.0037,
          0
        ],
        [
          0.899,
          0.013,
          -0.0214
        ],
        [
          0.0999,
          0.0019,
          -0.0102
        ],
        [
          0.5798,
          0.0112,
          -0.0149
        ],
        [
          0.4712,
          0.0056,
          0.0288
        ],
        [
          1.1096,
          0.013,
          0.0074
        ],
        [
          0.8078,
          -0.0149,
          -0.0195
        ],
        [
          1.3463,
          -0.0205,
          0.0168
        ],
        [
          1.5526,
          0.013,
          0.0186
        ],
        [
          0.9619,
          -0.0074,
          -0.0102
        ],
        [
          0.8468,
          0.0112,
          0.0195
        ],
        [
          1.2073,
          -0.0074,
          0.0074
        ],
        [
          1.2073,
          0.0074,
          -0.0288
        ],
        [
          1.3376,
          0,
          -0.014
        ],
        [
          1.7349,
          0.0186,
          -0.013
        ],
        [
          1.0618,
          -0.0074,
          0.0158
        ],
        [
          0.634,
          0.0205,
          0.0158
        ],
        [
          0.2128,
          0.0186,
          0.0102
        ],
        [
          0.3518,
          0.013,
          -0.0112
        ],
        [
          0.0022,
          0.013,
          0
        ],
        [
          0.9858,
          0.0186,
          0.0093
        ],
        [
          1.4874,
          0.0019,
          -0.0288
        ],
        [
          1.6264,
          -0.0112,
          -0.0056
        ],
        [
          1.4744,
          -0.0149,
          0.0214
        ],
        [
          1.4331,
          0.0074,
          0.0047
        ],
        [
          0.5711,
          -0.013,
          0.0223
        ],
        [
          0.5125,
          0,
          0.0028
        ],
        [
          0.4712,
          0.0149,
          -0.0214
        ],
        [
          0.2736,
          -0.0037,
          -0.0028
        ],
        [
          0.2866,
          -0.0074,
          0.027
        ],
        [
          0.786,
          0,
          0.0037
        ],
        [
          1.0553,
          0.0093,
          -0.0074
        ],
        [
          1.6807,
          0.013,
          0.027
        ],
        [
          1.6199,
          0,
          0.0149
        ],
        [
          1.3398,
          -0.0093,
          -0.0223
        ],
        [
          0.0521,
          -0.013,
          0.0214
        ],
        [
          0.1672,
          0.0168,
          -0.0074
        ],
        [
          1.166,
          0.0019,
          -0.0028
        ],
        [
          1.5699,
          -0.0112,
          -0.0121
        ]
      ]
    }
  },
  "shockRing": {
    "model": "assets/3d/effects/ring/ring.gltf",
    "sizeM": [
      0,
      4.7113,
      4.6981
    ],
    "bboxM": {
      "min": [
        0,
        -0.1842,
        -0.1974
      ],
      "max": [
        0,
        0.1842,
        0.1645
      ]
    },
    "drawScale": 0.7,
    "blend": "additive",
    "clip": "Explo",
    "animRate": 0.35,
    "animSeconds": 0.8571,
    "lifeSpan": 0.8,
    "offsetAlongNormalM": 0.188,
    "glowMax": 0.7,
    "notDrawn": [
      "ShockExplo",
      "EnergyImpact"
    ]
  },
  "bulletImpact": {
    "model": "assets/3d/effects/bulletimpact/bulletimpact.gltf",
    "sizeM": [
      0.8607,
      0.3727,
      0.2787
    ],
    "bboxM": {
      "min": [
        0,
        -0.1769,
        -0.1271
      ],
      "max": [
        0.8607,
        0.1958,
        0.1516
      ]
    },
    "drawScale": 0.28,
    "blend": "additive",
    "lifeSpan": 0.066667,
    "lifeSpanFrom": "AnimEnd of 'Hit' (1 frame at 30 fps, PlayAnim rate 0.5)",
    "offsetAlongNormalM": 0.024
  },
  "smokePuff": {
    "sheets": [
      "assets/3d/effects/fx/smokepuff-1.png",
      "assets/3d/effects/fx/smokepuff-2.png",
      "assets/3d/effects/fx/smokepuff-3.png",
      "assets/3d/effects/fx/smokepuff-4.png"
    ],
    "frames": 8,
    "pause": 0.05,
    "lifeSpan": 1.5,
    "animSeconds": 0.4,
    "drawScale": 2,
    "scaleGlow": 0.4,
    "risingRateMPerSec": 1.175,
    "offsetAlongNormalM": 0.212,
    "offsetAlongNormalMBy": {
      "wallHit": 0,
      "heavyWallHit": 0.188,
      "objectHit": 0.212
    },
    "sizeM": 1.504,
    "blend": "additive"
  },
  "spark": {
    "texture": "assets/3d/effects/fx/sparky.png",
    "lifeSpan": 1,
    "drawScale": 0.1,
    "sizeM": 0.0752,
    "speedMaxMPerSec": 4.7,
    "gravityMPerSec2": -22.325,
    "bounces": false,
    "diesOnContact": true,
    "offsetAlongNormalM": 0.188,
    "blend": "additive"
  },
  "chip": {
    "lifeSpan": 3,
    "launchAlongNormalMPerSec": 5.875,
    "scatterMaxMPerSec": 4.7,
    "drawScaleRange": [
      0.3,
      0.7
    ],
    "spinMaxRadPerSec": 19.1748,
    "bounces": true
  },
  "pock": {
    "textures": [
      "assets/3d/effects/fx/pock-0.png",
      "assets/3d/effects/fx/pock-1.png",
      "assets/3d/effects/fx/pock-2.png"
    ],
    "sizeM": 0.1429,
    "drawScale": 0.19,
    "lifeSeconds": [
      18,
      23
    ],
    "blend": "modulate"
  },
  "shellCase": {
    "model": "assets/3d/effects/shellcase/shellcase.gltf",
    "sizeM": [
      0.1675,
      0.0515,
      0.049
    ],
    "bboxM": {
      "min": [
        -0.0813,
        -0.0252,
        -0.0281
      ],
      "max": [
        0.0862,
        0.0263,
        0.0209
      ]
    },
    "drawScale": 1,
    "blend": "additive",
    "lifeSpan": 3,
    "sniperDrawScale": 2,
    "ejectMPerSec": {
      "forward": [
        1.504,
        2.632
      ],
      "right": [
        0.752,
        1.504
      ],
      "up": [
        3.76,
        4.888
      ]
    },
    "spawnOffsetM": {
      "enforcer": 0.47,
      "sniper": 0.705
    },
    "spinMaxRadPerSec": 9.5874,
    "gravityMPerSec2": -22.325,
    "bounces": true,
    "maxBounces": 3,
    "bounceRestitution": 0.5,
    "bounceStopChance": 0.85
  },
  "wallHit": {
    "enforcer": {
      "maxSparks": 3,
      "maxChips": 2,
      "chipOdds": 0.2
    },
    "enforcerDual": {
      "maxSparks": 1,
      "maxChips": 0,
      "chipOdds": 0.2
    },
    "sniper": {
      "maxSparks": 4,
      "maxChips": 2,
      "chipOdds": 0.5
    },
    "soundOdds": {
      "ricochet": 0.25,
      "impact1": 0.25,
      "impact2": 0.25,
      "silence": 0.25
    },
    "heavySoundOdds": {
      "ricochet": 0.5,
      "impact1": 0.25,
      "impact2": 0.25,
      "silence": 0
    },
    "ricochetPitch": [
      0.5,
      1.5
    ]
  },
  "sounds": {
    "chunkHit": "assets/audio/ut/chunkhit.mp3",
    "impact1": "assets/audio/ut/impact1.mp3",
    "impact2": "assets/audio/ut/impact2.mp3",
    "ricochet": "assets/audio/ut/ricochet.mp3"
  }
};

export { EFFECTS, FORWARD_AXIS };
