// GENERATED by scripts/gen-weapons.mjs — DO NOT EDIT.
//
// CTF-Face's weapons, as far as they are implemented. Damage and cadence are UT99's
// own numbers; the held model is the pickup mesh, the way the Enforcer already works.
//
// Six weapons: three hitscan, three that fly. A projectile weapon carries a "projectile"
// block the server uses to simulate it — speed in metres per second, splash radius in
// metres, and a wall-hit budget. Those are UT99's own figures converted once; the
// fireRate beside them is not: UT99 has no shot interval to read, so cadence is chosen.

const WEAPONS = {
  "enforcer": {
    "name": "Enforcer",
    "damage": 17,
    "fireRate": 4,
    "model": null,
    "pickup": null,
    "sound": "assets/audio/ut/e_shot.mp3",
    "view": {
      "model": "assets/3d/viewmodels/enforcer/enforcer.gltf",
      "rotationDeg": [
        0,
        90,
        0
      ],
      "offsetUU": [
        3.3,
        -2,
        -3
      ],
      "fireOffsetUU": [
        0,
        -10,
        -4
      ],
      "sizeM": [
        0.0281,
        0.0556,
        0.1227
      ]
    }
  },
  "sniper": {
    "name": "Sniper Rifle",
    "damage": 45,
    "fireRate": 0.6666666666666666,
    "model": "assets/3d/pickups/SniperRifle/SniperRifle.gltf",
    "pickup": "weapon-sniper",
    "headshotDamage": 100,
    "sound": "assets/audio/ut/sniperfire.mp3",
    "view": {
      "model": "assets/3d/viewmodels/sniper/sniper.gltf",
      "rotationDeg": [
        0,
        90,
        0
      ],
      "offsetUU": [
        5,
        -1.6,
        -1.7
      ],
      "fireOffsetUU": [
        0,
        -5,
        -2
      ],
      "sizeM": [
        0.3527,
        0.0835,
        0.1028
      ]
    }
  },
  "shock": {
    "name": "Shock Rifle",
    "damage": 40,
    "fireRate": 1.6666666666666667,
    "model": "assets/3d/pickups/ShockRifle/ShockRifle.gltf",
    "pickup": "weapon-shock",
    "sound": "assets/audio/ut/tazerfire.mp3",
    "view": {
      "model": "assets/3d/viewmodels/shock/shock.gltf",
      "rotationDeg": [
        0,
        90,
        0
      ],
      "offsetUU": [
        4.4,
        -1.7,
        -1.6
      ],
      "fireOffsetUU": [
        10,
        -5,
        -8
      ],
      "sizeM": [
        0.1797,
        0.0372,
        0.0489
      ]
    }
  },
  "rocket": {
    "name": "Rocket Launcher",
    "damage": 75,
    "fireRate": 0.9090909090909091,
    "model": "assets/3d/pickups/UT_Eightball/UT_Eightball.gltf",
    "pickup": "weapon-rocket",
    "sound": "assets/audio/ut/ignite.mp3",
    "projectile": {
      "type": "rocket",
      "speed": 21.15,
      "splashRadius": 5.17,
      "lifeMs": 6000,
      "bounces": 0,
      "model": "assets/3d/projectiles/rocket/rocket.gltf"
    },
    "explosion": {
      "atlas": "assets/3d/projectiles/fx/rocket-explosion.png",
      "frames": 8,
      "cols": 4,
      "rows": 2,
      "lifeMs": 700,
      "size": 4.211,
      "blend": "additive",
      "sound": "assets/audio/ut/explo1.mp3"
    },
    "view": {
      "model": "assets/3d/viewmodels/rocket/rocket.gltf",
      "rotationDeg": [
        0,
        -90,
        0
      ],
      "offsetUU": [
        2.4,
        -1,
        -2.2
      ],
      "fireOffsetUU": [
        10,
        -5,
        -8.8
      ],
      "sizeM": [
        0.1658,
        0.0682,
        0.0854
      ]
    }
  },
  "ripper": {
    "name": "Ripper",
    "damage": 30,
    "fireRate": 1.6666666666666667,
    "model": "assets/3d/pickups/ripper/ripper.gltf",
    "pickup": "weapon-ripper",
    "sound": "assets/audio/ut/startblade.mp3",
    "headshotDamage": 105,
    "projectile": {
      "type": "ripper",
      "speed": 30.55,
      "splashRadius": 0,
      "lifeMs": 6000,
      "bounces": 6,
      "model": "assets/3d/projectiles/ripper/ripper.gltf"
    },
    "view": {
      "model": "assets/3d/viewmodels/ripper/ripper.gltf",
      "rotationDeg": [
        0,
        90,
        0
      ],
      "offsetUU": [
        3,
        -1.6,
        -2.4
      ],
      "fireOffsetUU": [
        0,
        -15,
        -13
      ],
      "sizeM": [
        0.1598,
        0.0632,
        0.0219
      ]
    }
  },
  "redeemer": {
    "name": "Redeemer",
    "damage": 1000,
    "fireRate": 0.4,
    "model": "assets/3d/pickups/WarheadLauncher/WarheadLauncher.gltf",
    "pickup": "weapon-redeemer",
    "sound": "assets/audio/ut/warheadshot.mp3",
    "projectile": {
      "type": "redeemer",
      "speed": 14.1,
      "splashRadius": 7.05,
      "lifeMs": 6000,
      "bounces": 0,
      "model": "assets/3d/projectiles/redeemer/redeemer.gltf"
    },
    "explosion": {
      "atlas": "assets/3d/projectiles/fx/redeemer-explosion.png",
      "frames": 18,
      "cols": 6,
      "rows": 3,
      "lifeMs": 1000,
      "size": 8.422,
      "blend": "additive",
      "sound": "assets/audio/ut/warexplo.mp3"
    },
    "view": {
      "model": "assets/3d/viewmodels/redeemer/redeemer.gltf",
      "rotationDeg": [
        22.5,
        90,
        -87.1875
      ],
      "offsetUU": [
        1.8,
        1,
        -1.89
      ],
      "fireOffsetUU": [
        18,
        0,
        -10
      ],
      "sizeM": [
        0.1393,
        0.0911,
        0.0516
      ]
    }
  }
};

const DEFAULT_WEAPON = "enforcer";
const WEAPON_BY_PICKUP = {
  "weapon-sniper": "sniper",
  "weapon-shock": "shock",
  "weapon-rocket": "rocket",
  "weapon-ripper": "ripper",
  "weapon-redeemer": "redeemer"
};
const PAWN = {"radius":0.4,"height":1.833,"headshotAboveCentre":0.568};
const PICKUP_SOUND = "assets/audio/ut/weaponpickup.mp3";

/** The weapon for an id, falling back to the one everyone spawns with. */
function weapon(id) {
  return WEAPONS[id] || WEAPONS[DEFAULT_WEAPON];
}

export { WEAPONS, DEFAULT_WEAPON, WEAPON_BY_PICKUP, PAWN, PICKUP_SOUND, weapon };
