// GENERATED by scripts/gen-weapons.mjs — DO NOT EDIT.
//
// CTF-Face's weapons, as far as they are implemented. Damage and cadence are UT99's
// own numbers; the held model is the pickup mesh, the way the Enforcer already works.
//
// Six weapons: three hitscan, three that fly. A projectile weapon carries a "projectile"
// block the server uses to simulate it — speed in metres per second, splash radius in
// metres, and a wall-hit budget. Those are UT99's own figures converted once; the
// fireRate beside them is not: UT99 has no shot interval to read, so cadence is chosen.

const WEAPONS = {
  "enforcer": {
    "name": "Enforcer",
    "damage": 17,
    "fireRate": 4,
    "model": null,
    "pickup": null
  },
  "sniper": {
    "name": "Sniper Rifle",
    "damage": 45,
    "fireRate": 0.6666666666666666,
    "model": "assets/3d/pickups/SniperRifle/SniperRifle.gltf",
    "pickup": "weapon-sniper"
  },
  "shock": {
    "name": "Shock Rifle",
    "damage": 40,
    "fireRate": 1.6666666666666667,
    "model": "assets/3d/pickups/ShockRifle/ShockRifle.gltf",
    "pickup": "weapon-shock"
  },
  "rocket": {
    "name": "Rocket Launcher",
    "damage": 75,
    "fireRate": 0.9090909090909091,
    "model": "assets/3d/pickups/UT_Eightball/UT_Eightball.gltf",
    "pickup": "weapon-rocket",
    "projectile": {
      "type": "rocket",
      "speed": 21.15,
      "splashRadius": 5.17,
      "lifeMs": 6000,
      "bounces": 0,
      "model": "assets/3d/projectiles/rocket/rocket.gltf"
    },
    "explosion": {
      "atlas": "assets/3d/projectiles/fx/rocket-explosion.png",
      "frames": 8,
      "cols": 4,
      "rows": 2,
      "lifeMs": 700,
      "size": 4.211,
      "blend": "additive"
    }
  },
  "ripper": {
    "name": "Ripper",
    "damage": 30,
    "fireRate": 1.6666666666666667,
    "model": "assets/3d/pickups/ripper/ripper.gltf",
    "pickup": "weapon-ripper",
    "projectile": {
      "type": "ripper",
      "speed": 30.55,
      "splashRadius": 0,
      "lifeMs": 6000,
      "bounces": 6,
      "model": "assets/3d/projectiles/ripper/ripper.gltf"
    }
  },
  "redeemer": {
    "name": "Redeemer",
    "damage": 1000,
    "fireRate": 0.4,
    "model": "assets/3d/pickups/WarheadLauncher/WarheadLauncher.gltf",
    "pickup": "weapon-redeemer",
    "projectile": {
      "type": "redeemer",
      "speed": 14.1,
      "splashRadius": 7.05,
      "lifeMs": 6000,
      "bounces": 0,
      "model": "assets/3d/projectiles/redeemer/redeemer.gltf"
    },
    "explosion": {
      "atlas": "assets/3d/projectiles/fx/redeemer-explosion.png",
      "frames": 18,
      "cols": 6,
      "rows": 3,
      "lifeMs": 1000,
      "size": 8.422,
      "blend": "additive"
    }
  }
};

const DEFAULT_WEAPON = "enforcer";
const WEAPON_BY_PICKUP = {
  "weapon-sniper": "sniper",
  "weapon-shock": "shock",
  "weapon-rocket": "rocket",
  "weapon-ripper": "ripper",
  "weapon-redeemer": "redeemer"
};
const PAWN = {"radius":0.4,"height":1.833};

/** The weapon for an id, falling back to the one everyone spawns with. */
function weapon(id) {
  return WEAPONS[id] || WEAPONS[DEFAULT_WEAPON];
}

export { WEAPONS, DEFAULT_WEAPON, WEAPON_BY_PICKUP, PAWN, weapon };
