#!/usr/bin/env node
// gen-weapons.mjs — write the weapon table for both processes from one source.
//
//   node scripts/gen-weapons.mjs          # rewrite src/shared/weapons.js + server/weapons.js
//   node scripts/gen-weapons.mjs --check  # fail if out of date
//
// The server owns damage and cadence (a client never gets to pick either) and the
// client owns what the weapon looks like in your hands. Both have to agree on the id,
// so one table generates both — the same arrangement as the character roster.
//
// NUMBERS ARE UT99's, from Botpack's own class defaults, not invented:
//   Enforcer      17 damage, 4 shots/s   (Botpack.Enforcer HitDamage=17)
//   Sniper Rifle  45 damage, 1.5 s cycle — the reason CTF-Face has towers
//   Shock Rifle   40 damage, 0.6 s cycle — primary fire, the instant-hit beam
//
// The held model is the PICKUP mesh, the same way the Enforcer already works: what you
// see on the pedestal is literally what you pick up, and it costs no extra art.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(HERE, "..");
const OUT_SHARED = path.join(ROOT, "src", "shared", "weapons.js");
const OUT_SERVER = path.join(ROOT, "server", "weapons.js");
const CHECK = process.argv.includes("--check");

const WEAPONS = {
  enforcer: {
    name: "Enforcer",
    damage: 17,
    fireRate: 4, // shots per second
    model: null, // the markup weapon in index.html; every player spawns holding it
    pickup: null, // CTF-Face has no Enforcer pickup, as in the original
  },
  sniper: {
    name: "Sniper Rifle",
    damage: 45,
    fireRate: 1 / 1.5,
    model: "assets/3d/pickups/SniperRifle/SniperRifle.gltf",
    pickup: "weapon-sniper",
  },
  shock: {
    name: "Shock Rifle",
    damage: 40,
    fireRate: 1 / 0.6,
    model: "assets/3d/pickups/ShockRifle/ShockRifle.gltf",
    pickup: "weapon-shock",
  },
};

const DEFAULT = "enforcer";
// pickup type -> weapon id, for the server's claim handler and the client's HUD.
const BY_PICKUP = Object.fromEntries(
  Object.entries(WEAPONS)
    .filter(([, w]) => w.pickup)
    .map(([id, w]) => [w.pickup, id])
);

const header = `// GENERATED by scripts/gen-weapons.mjs — DO NOT EDIT.
//
// CTF-Face's weapons, as far as they are implemented. Damage and cadence are UT99's
// own numbers; the held model is the pickup mesh, the way the Enforcer already works.
//
// NOT HERE YET: the Rocket Launcher, Ripper and Redeemer. All three are projectile
// weapons — travel time, splash, bouncing blades — and the game resolves every shot as
// an instant hit. Their pickups stand on the map and respawn, and picking one up does
// nothing, which is honest: arming someone with a rocket launcher that fires hitscan
// pistol rounds would be a worse lie than leaving it inert.
`;

const shared = `${header}
const WEAPONS = ${JSON.stringify(WEAPONS, null, 2)};

const DEFAULT_WEAPON = ${JSON.stringify(DEFAULT)};
const WEAPON_BY_PICKUP = ${JSON.stringify(BY_PICKUP, null, 2)};

/** The weapon for an id, falling back to the one everyone spawns with. */
function weapon(id) {
  return WEAPONS[id] || WEAPONS[DEFAULT_WEAPON];
}

export { WEAPONS, DEFAULT_WEAPON, WEAPON_BY_PICKUP, weapon };
`;

const server = `${header}
const WEAPONS = ${JSON.stringify(
  Object.fromEntries(Object.entries(WEAPONS).map(([id, w]) => [id, { name: w.name, damage: w.damage, fireRate: w.fireRate }])),
  null,
  2
)};

const DEFAULT_WEAPON = ${JSON.stringify(DEFAULT)};
const WEAPON_BY_PICKUP = ${JSON.stringify(BY_PICKUP, null, 2)};

/** The weapon for an id, falling back to the one everyone spawns with. */
function weapon(id) {
  return WEAPONS[id] || WEAPONS[DEFAULT_WEAPON];
}

module.exports = { WEAPONS, DEFAULT_WEAPON, WEAPON_BY_PICKUP, weapon };
`;

if (CHECK) {
  const stale = [[OUT_SHARED, shared], [OUT_SERVER, server]].filter(([f, want]) => {
    const cur = fs.existsSync(f) ? fs.readFileSync(f, "utf8") : "";
    return cur !== want;
  });
  if (stale.length) {
    console.error(`${stale.map(([f]) => path.relative(ROOT, f)).join(", ")} out of date — run: node scripts/gen-weapons.mjs`);
    process.exit(1);
  }
  console.log("weapon table is up to date.");
  process.exit(0);
}
fs.writeFileSync(OUT_SHARED, shared);
fs.writeFileSync(OUT_SERVER, server);
console.log(
  `wrote the weapon table — ${Object.keys(WEAPONS).length} weapons\n` +
    Object.entries(WEAPONS).map(([id, w]) => `  ${id.padEnd(9)} ${String(w.damage).padStart(2)} dmg  ${w.fireRate.toFixed(2)}/s  ${w.pickup || "(spawn)"}`).join("\n")
);
